#!/usr/bin/env python3
"""Step 5 for facelove-paint-wall: act map (E4 rows, one picture per phrase §27), wardrobe map per story day (§21/§14A),
written to act_map.json and wardrobe.json. Hook rows are written at step 6 (L1 is Hook 1).
Face arc (F13): bare-faced (N-BEFORE) from the hook through the demonstration, the stick put on in the Scene 7 hero macro,
finished (N-AFTER) from Scene 8 on — the proof on one face in one sitting."""
import json, pathlib
HERE = pathlib.Path(__file__).parent
SHL = dict(source="tall dressing-room window, left-hand wall", key_side="L", time="midday", arc="bright clean daylight", kelvin=5600)
WAL = dict(source="tall dressing-room window, seen on the right from the wall side", key_side="R", time="midday", arc="bright clean daylight, raking the plaster", kelvin=5600)
PST = dict(source="the same window, a grey morning years ago", key_side="L", time="morning", arc="flat grey morning, a little dim", kelvin=6500)
def F(plane, dof): return {"plane": plane, "dof": dof, "rack": None, "moving_subject": False}
def BR(beat, act, line, day, loc, cast, h, s, sc, why, focus, light, face, prod, action, pace, camera, plate, fg="clean", staging="", pin_end=False, state=None, **kw):
    r = dict(beat=beat, group=act, act=act, type="BR", line=line, story_day=day, location=loc, cast=cast, subject=kw.pop("subject", cast[0] if cast else "PRODUCT"),
             height=h, side=s, scale=sc, fg=fg, why=why, mode=1, focus=focus, light=light, face=face, product_beat=prod,
             action=action, pace=pace, camera=camera, staging=staging, pin_end=pin_end, plate=plate, face_state=state, layout="full",
             duration="pending-master", max=None)
    r.update(kw); return r
def TH(beat, act, line, state, seed, loc="L-SHELF"):
    return dict(beat=beat, group=act, act=act, type="TH", line=line, story_day="REC", location=loc, cast=["N"], subject="N",
                mode=1, face=True, face_state=state, seed=seed, layout="full")
TRIPOD = "phone on a tripod at chest height, locked, no travel"

R = [
 # ---- Act 1 · Scenes 2–3 · the years of foundations (L2, L3) ----
 TH("TH-01", "Act 1", "I am fifty seven.", "N-BEFORE", "N-VOICE-SHELF-B"),
 BR("B01", "Act 1", "And for years I felt like my own face", "REC", "L-SHELF", ["N"], "eye", "three-quarter-back", "MEDIUM",
    "from behind her shoulder — we look along the shelf with her", F("eyes", "deep"), SHL, True, False,
    "she turns her head from the lens and runs her eyes slowly along the rows of unlabelled bottles, one hand resting on the white dresser", "one slow look along the shelf, about 2 s",
    TRIPOD, "L-SHELF, the shelf wall, from her left shoulder", state="N-BEFORE"),
 BR("B02", "Act 1", "had quietly turned on me.", "REC", "L-SHELF", ["N"], "eye", "ots", "CU",
    "over her shoulder into the hand mirror — her face as she sees it", F("eyes", "medium"), SHL, True, False,
    "she lifts a round hand mirror to her face and holds it still; in the glass, her bare tired face looks back", "one lift, then still",
    "handheld over her shoulder, slight sway, no travel", "the hand mirror against the shelf wall", fg="through", state="N-BEFORE"),
 BR("B03", "Act 1", "The dull, tired skin.", "REC", "L-SHELF", ["N"], "high", "front", "ECU",
    "a little above — the honest, unflattering look", F("eyes", "shallow"), SHL, True, False,
    "in the mirror, her bare cheek and eye: dull, sallow, matte skin; she blinks once, slowly", "one slow blink",
    "handheld, still", "the mirror's glass, full frame", state="N-BEFORE"),
 BR("B04", "Act 1", "The deep lines.", "REC", "L-SHELF", ["N"], "eye", "profile", "ECU",
    "side-on so the creases throw their shadows", F("eyes", "shallow"), SHL, True, False,
    "side-on, her outer eye and temple: the deep crow's feet hold their shadows as her eyes narrow a little, then relax", "one slow squint and release, about 2 s",
    "handheld, still", "her left eye in profile, window behind the phone", state="N-BEFORE", whole="one crease-held moment; the phrase is under 2 s and joins the dark-circle beat in the cut"),
 BR("B05", "Act 1", "The dark circles that made me look worn out", "REC", "L-SHELF", ["N"], "low", "three-quarter", "CU",
    "from just below — the circles under the eyes read in full", F("eyes", "shallow"), SHL, True, False,
    "her eyes lift from the mirror to the lens; the dark circles under both eyes plain in the window light", "one slow look up",
    "handheld, slight sway", "her face three-quarter, window left", state="N-BEFORE"),
 TH("TH-02", "Act 1", "even on a good day. So I did what we all do.", "N-BEFORE", "N-VOICE-SHELF-B"),
 BR("B06", "Act 1", "I bought the next foundation, then the next,", "PAST", "L-SHELF", ["N"], "eye", "front", "CU",
    "square on the shelf — the row growing", F("hands", "medium"), PST, False, False,
    "her hand sets one more unlabelled bottle at the end of a row on the shelf, then a second beside it", "two set-downs, about 2 s",
    TRIPOD, "the shelf, square on, one row", state="N-BEFORE", subject="N-HANDS"),
 BR("B07", "Act 1", "then the two hundred dollar one,", "PAST", "L-SHELF", ["N"], "high", "three-quarter", "CU",
    "from above, like unwrapping something precious", F("hands", "medium"), PST, False, False,
    "her hands lift a heavy faceted glass bottle with a gold cap out of white tissue paper in a plain cream box", "one slow lift",
    "handheld above the dresser, still", "the dresser top, from above", state="N-BEFORE", subject="N-HANDS"),
 BR("B08", "Act 1", "always sure the next one would finally fix it.", "PAST", "L-SHELF", ["N"], "low", "three-quarter", "MCU",
    "a little low — her hope, before it fails", F("eyes", "medium"), PST, True, False,
    "at the hand mirror she dots the new foundation on her cheek with one fingertip and looks, hopeful", "three small dots, about 2 s",
    "handheld, slight sway", "her face three-quarter, window left", state="N-BEFORE"),
 TH("TH-03", "Act 1", "Every single one did the same thing.", "N-BEFORE", "N-VOICE-SHELF-B"),
 BR("B09", "Act 1", "It sat on top, sank into my lines,", "PAST", "L-SHELF", ["N"], "eye", "profile", "ECU",
    "macro side-on: the cake on the crease is the problem", F("eyes", "shallow"), PST, True, False,
    "macro of her outer eye and cheek: a flat beige foundation sits cakey on the skin and has settled into every crow's foot, each crease a darker line of product; she blinks once", "one blink",
    "handheld macro, still", "her left cheek in profile", state="N-BEFORE+OLD-FOUNDATION"),
 BR("B10", "Act 1", "oxidized, and left me looking more tired than my bare face.", "PAST", "L-SHELF", ["N"], "eye", "ots", "MCU",
    "over her shoulder into the hand mirror — the let-down", F("eyes", "medium"), PST, True, False,
    "in the hand mirror, her caked face: the foundation gone patchy and orange along the jaw against her paler neck; she lowers the mirror slowly", "one slow lowering, about 2 s",
    "handheld over her shoulder, still", "the hand mirror against the shelf wall", fg="through", state="N-BEFORE+OLD-FOUNDATION"),
 TH("TH-04", "Act 1", "I was sure something was wrong with me. It took me years to find out the real reason.", "N-BEFORE", "N-VOICE-SHELF-B"),
 # ---- Act 2 · Scenes 4–5 · the paint wall (L4, L5) ----
 BR("B11", "Act 2", "Think of your skin like a wall", "REC", "L-WALL", ["N"], "low", "front", "WIDE",
    "low and wide — the analogy built life-size, she presents it", F("deep", "deep"), WAL, True, False,
    "she steps once to stand beside the bare warm plaster wall, the beige foundation bottle in one hand, and lays her other palm flat on the wall", "one step and a palm to the wall, about 2 s",
    TRIPOD, "L-WALL, the whole wall, from the shelf side", state="N-BEFORE", hero_why="the room becomes the analogy"),
 TH("TH-05", "Act 2", "you are trying to paint to look flawless.", "N-BEFORE", "N-VOICE-WALL-B", loc="L-WALL"),
 BR("B12", "Act 2", "Every foundation you have ever bought", "REC", "L-WALL", ["N"], "eye", "three-quarter", "MCU",
    "level, like a teacher holding up the example", F("product", "medium"), WAL, True, False,
    "she raises the beige foundation bottle to shoulder height beside the wall and holds it there, eyes on the lens", "one raise, then still",
    TRIPOD, "her at the wall, three-quarter", state="N-BEFORE"),
 BR("B13", "Act 2", "works exactly like a pre-mixed can of paint from a factory,", "REC", "L-WALL", ["N"], "overhead", "front", "CU",
    "top-down into the can — the one flat factory colour", F("product", "deep"), WAL, False, False,
    "top-down: the open paint can of flat pinkish-beige paint on the drop cloth; her hand sets the beige foundation bottle down right beside it", "one set-down",
    "handheld straight down, still", "the paint kit on the drop cloth from above", state=None, subject="PAINT"),
 TH("TH-06", "Act 2", "in one fixed shade, before anyone ever saw your wall.", "N-BEFORE", "N-VOICE-WALL-B", loc="L-WALL"),
 BR("B14", "Act 2", "You bring it home, put it on,", "REC", "L-WALL", ["N"], "eye", "three-quarter-back", "MEDIUM",
    "behind her shoulder — we watch the coat go on", F("deep", "medium"), WAL, True, False,
    "she rolls the beige paint up the bare wall in one long, slow stroke", "one stroke, about 2 s",
    TRIPOD, "the wall from behind her right shoulder", state="N-BEFORE"),
 BR("B15", "Act 2", "and it is never quite your color.", "REC", "L-WALL", ["N"], "low", "front", "FULL",
    "low and square — the mismatch across the whole wall", F("deep", "deep"), WAL, True, False,
    "she steps back from the wall, roller lowered; the rolled stripe sits flat and pinkish against the warm plaster around it, plainly the wrong colour; she tilts her head", "one step back and a head tilt",
    TRIPOD, "L-WALL, square on", state="N-BEFORE"),
 BR("B16", "Act 2", "It sits there as an obvious coat.", "REC", "L-WALL", [], "high", "three-quarter", "ECU",
    "macro across the edge — a skin sitting on top", F("foreground", "shallow"), WAL, False, False,
    "macro on the edge of the rolled stripe: a flat ridge of beige paint sitting on top of the plaster, a hard edge against the bare wall", "the light shifts very slightly, nothing else moves",
    "handheld macro, still", "the stripe's edge on the wall", state=None, subject="WALL"),
 BR("B17", "Act 2", "And on a wall with any texture or fine cracks,", "REC", "L-WALL", [], "eye", "front", "ECU",
    "square macro — the cracks read as skin's lines", F("foreground", "shallow"), WAL, False, False,
    "macro, square on the plaster: the roller's beige coat slides over a patch of fine hairline cracks and sinks into them, each crack turning to a darker line", "one slow pass of paint, about 3 s",
    "handheld macro, still", "a patch of the cracked plaster", state=None, subject="WALL", pair_note="ED02: B18 is made from this frame — the cracks and the skin lines mirror each other"),
 BR("B18", "Act 2", "like skin over fifty, it sinks straight into them and makes them worse.", "PAST", "L-SHELF", ["N"], "eye", "front", "ECU",
    "the same square macro on her cheek — the cracks are her lines", F("foreground", "shallow"), PST, True, False,
    "macro, square on her cheek, framed exactly like the wall: a beige foundation sinks into her fine lines, each line turning to a darker line of product in the same pattern as the wall's cracks", "one slow settling, about 3 s",
    "handheld macro, still", "her cheek, matched to B17", state="N-BEFORE+OLD-FOUNDATION", mirror_of="B17",
    whole="one continuous settling of the product into the lines — nothing else changes in the picture"),
 # ---- Act 3 · Scenes 6–7 · the opposite (L6, L7) ----
 TH("TH-07", "Act 3", "A can of paint can only ever be the one color it was mixed as.", "N-BEFORE", "N-VOICE-WALL-B", loc="L-WALL"),
 BR("B19", "Act 3", "This does the opposite. It does not come in a shade.", "REC", "L-WALL", ["N"], "eye", "three-quarter", "MCU",
    "three-quarter at the wall — she turns from the paint to the stick", F("product", "medium"), WAL, True, True,
    "she sets the beige bottle down on the drop cloth by the paint can, straightens and holds the closed violet FACELOVE stick up beside her face, wordmark to the lens", "one set-down and one raise, about 3 s",
    TRIPOD, "her at the wall, square", pin_end=True, state="N-BEFORE"),
 BR("B20", "Act 3", "It comes out pure white. I know what you are thinking. Stay with me.", "REC", "L-WALL", ["N"], "low", "three-quarter", "CU",
    "a little low — the reveal, and her knowing smile", F("product", "medium"), WAL, True, True,
    "she draws the cap straight off the balm end and turns the white balm toward the lens, a knowing smile", "one cap off, then still",
    "handheld, slight sway", "her face three-quarter with the stick", pin_end=True, state="N-BEFORE",
    whole="one move — the cap off and the white held up; the smile carries 'I know what you are thinking'"),
 BR("B21", "Act 3", "It reads the warmth of your own skin and becomes your exact shade, right there on your face. No shade to pick. No wrong match. It adapts as it goes on.", "REC", "L-WALL", ["N"], "eye", "profile", "ECU",
    "one unbroken macro side-on: white ahead of the brush, her shade behind it (ED03)", F("product", "shallow"), WAL, True, True,
    "one continuous macro of her bare cheek: the balm's flat crest lays a white stripe, then the brush end sweeps through it in slow circles — ahead of the crown it is still white, behind it it is her own shade — until the cheek is one even tone, every line still there", "slow circles, about 10 s, never cut",
    "handheld macro, still", "her right cheek in profile", state="N-BEFORE->N-AFTER", hero_why="the product's whole promise in one shot",
    whole="ED03: one continuous unbroken shot, no cut during the colour change (the brief's non-negotiable)"),
 # ---- Act 4 · Scenes 8–9 · the result (L8, L9) ----
 BR("B22", "Act 4", "It covers the lines, the dark circles, the tired.", "REC", "L-SHELF", ["N"], "eye", "profile", "MCU",
    "she turns from profile into the light — the result revealed", F("eyes", "medium"), SHL, True, False,
    "she turns her finished face slowly from profile to the lens in the window light; the tone even, the dark circles gone, every line still there", "one slow turn, about 3 s",
    TRIPOD, "L-SHELF, her face by the window", state="N-AFTER", hero_why="the after on the same face"),
 TH("TH-08", "Act 4", "And it still looks like my own skin. Not a thick coat sitting on top.", "N-AFTER", "N-VOICE-SHELF-A"),
 BR("B23", "Act 4", "My skin, on its best day. Finally the right match,", "REC", "L-SHELF", ["N"], "eye", "front", "CU",
    "square on — the flat bottle against her finished cheek", F("eyes", "medium"), SHL, True, False,
    "she holds the beige foundation bottle up beside her finished cheek and looks at the lens: the flat factory beige next to her even, matched skin", "one raise, then still",
    "handheld, slight sway", "her face square with the bottle", state="N-AFTER"),
 BR("B24", "Act 4", "instead of a guess from a factory.", "REC", "L-SHELF", ["N"], "high", "three-quarter-back", "MEDIUM",
    "from above her shoulder — the bottle goes back with the failures", F("hands", "deep"), SHL, False, False,
    "she sets the beige bottle back on the shelf among the forty others and lets go", "one set-back",
    TRIPOD, "the shelf from behind her right shoulder", state="N-AFTER"),
 TH("TH-09", "Act 4", "It was never your skin, and it was never your age. It was a color that was never yours to begin with. And now that I know that, I am not going back.", "N-AFTER", "N-VOICE-SHELF-A"),
 # ---- Act 5 · Scene 10 · CTA (L10) ----
 TH("TH-10", "Act 5", "It is called FACELOVE, and I have linked it below. Right now you get", "N-AFTER", "N-VOICE-SHELF-A"),
 BR("B25", "Act 5", "two Foundation Sticks for almost the price of one,", "REC", "L-SHELF", ["N"], "high", "front", "CU",
    "from above the dresser — the deal laid out", F("product", "medium"), SHL, False, True,
    "her hand sets a second closed FACELOVE stick upright beside the first on the white dresser top, both wordmarks to the lens", "one set-down, about 1 s",
    "handheld above, still", "the dresser top", pin_end=True, state=None, subject="PRODUCT"),
 BR("B26", "Act 5", "plus a free primer, a mystery gift,", "REC", "L-SHELF", ["N"], "eye", "three-quarter", "CU",
    "level with the dresser — the bundle grows", F("product", "medium"), SHL, False, True,
    "her hand sets the primer and then the small mystery gift box beside the two sticks, the box lid ajar on a fold of white tissue", "two set-downs, about 2 s",
    "handheld, still", "the dresser top, low and level", pin_end=True, state=None, subject="PRODUCT"),
 TH("TH-11", "Act 5", "and free shipping and a full thirty day money back guarantee.", "N-AFTER", "N-VOICE-SHELF-A"),
 BR("B27", "Act 5", "Stop paying for a color that was never yours.", "REC", "L-SHELF", [], "eye", "front", "CU",
    "the clean hero shot — the stick alone in soft light (VN10)", F("product", "shallow"), SHL, False, True,
    "the closed FACELOVE stick stands upright on the white dresser and turns slowly a quarter turn in the soft window light, the wordmark coming round to the lens", "a quarter turn, about 3 s",
    TRIPOD, "the stick on the dresser, the shelf soft behind", pin_end=True, state=None, subject="PRODUCT", hero_why="the brief's clean hero shot"),
 TH("TH-12", "Act 5", "Get the one that becomes it.", "N-AFTER", "N-VOICE-SHELF-A"),
]
json.dump(R, open(HERE / "act_map.json", "w"), indent=1, ensure_ascii=False)

W = {"names": {"N": "the narrator"},
 "days": [
  {"day": "PAST", "event": "the years of trying foundations — mornings at her shelf", "source": "stated: 'for years… I bought the next foundation, then the next, then the two hundred dollar one'",
   "outfits": {"N": "a soft heather-grey crew-neck sweater, hair pushed back behind the ears, bare face then the old beige foundation (N-BEFORE)"},
   "events": [{"id": "PAST-E1", "location": "L-SHELF", "visibility": "VISIBLE", "beats": ["B06", "B07", "B08", "B09", "B10", "B18"]}]},
  {"day": "REC", "event": "today — filming the demonstration in her dressing room", "source": "stated: 'I can show you exactly why in about thirty seconds'",
   "outfits": {"N": "sheet outfit: the oatmeal linen blazer open over a white ribbed tank, cream wide-leg trousers, nude block-heel mules — bare face until the Scene 7 macro, the stick on after (N-BEFORE → N-AFTER)"},
   "events": [{"id": "REC-E1", "location": "L-SHELF", "visibility": "VISIBLE", "beats": ["B01", "B02", "B03", "B04", "B05"]},
              {"id": "REC-E2", "location": "L-WALL", "visibility": "VISIBLE", "beats": ["B11", "B12", "B13", "B14", "B15", "B16", "B17", "B19", "B20", "B21"]},
              {"id": "REC-E3", "location": "L-SHELF", "visibility": "VISIBLE", "beats": ["B22", "B23", "B24", "B25", "B26", "B27"]}]}],
 "talking_heads": [{"day": "REC", "subject": "N", "outfit": "the oatmeal linen blazer over the white tank (one sitting: bare face at the shelf and the wall, the stick on from Scene 8)",
                    "beats": [r["beat"] for r in R if r["type"] == "TH"]}]}
json.dump(W, open(HERE / "wardrobe.json", "w"), indent=1, ensure_ascii=False)
print(len(R), "rows,", sum(r["type"] == "BR" for r in R), "B-roll,", sum(r["type"] == "TH" for r in R), "TH")
