#!/usr/bin/env python3
"""Act 1 clips (§35A, Mode 2): one Kling 3.0 clip per confirmed beat image, the motionPlan verbatim, ≤ 1,000 chars, preflight kind broll.
python3 clips/build_act1_clips.py <BEAT>:<imgver> ...  → clips/<BEAT>.v1.call.json + .prompt.txt, runs preflight."""
import json, subprocess, sys
from pathlib import Path
H = Path(__file__).parent; B = H.parent
PF = B / "../../.claude/skills/ai-prompt-engineer/scripts/preflight.py"
rows = {r["beat"]: r for r in json.load(open(B / "work/actmap_rows.json"))}
urls = json.load(open(B / "body/urls.json")); jobs = json.load(open(B / "body/jobs.json"))
MOTION = {
 "P-03a": "In close on her knee, her right hand hauls the brace's top strap up over the kneecap in one pull, holds a moment, and the brace sags back down below the kneecap as the hand eases; her left hand stays on the table edge; the knee, the slipper and the kitchen behind stay exactly as in the frame. Stylized 3D animation, exactly on model from the frame, the brace rigid in shape. No camera travel; nobody else; no cut; the brace never changes design.",
 "P-04a": "Overhead on the table, her two hands push outward once and the heap slides apart a little across the wood — a bottle tips and rolls a few centimetres, a sleeve slips — then the hands rest flat on the table; nothing new appears on it. Stylized 3D animation, every object exactly as in the frame, rigid in shape. No camera travel; nobody else; no cut; the hands stay in frame.",
 "P-04b": "The therapist's two hands bend her right knee a little further toward her chest, slowly, and hold it there; she stays on her back, head on the pillow, eyes on the ceiling, hands folded on her stomach; the therapist's head stays out of frame above. Stylized 3D animation, both exactly on model from the frame. No camera travel; no third person; no cut; nobody turns to the lens.",
 "P-05a": "The back of her right hand pushes the heap once across the table away from her, the bottles and sleeves sliding to the far edge, then she sits back in the chair, shoulders dropping, eyes on nothing past the lens, her left hand slack in her lap. Stylized 3D animation, exactly on model from the frame, every object rigid. No camera travel; nobody else; no cut; she never looks into the lens.",
}
DUR = {"P-03a": 5, "P-04a": 4, "P-04b": 5, "P-05a": 6}
MOTION["P-01b"] = "In close at step height, she steps backwards down the flight: the lower slipper's heel settles on the step below and takes her weight, then the upper foot lifts and reaches back and down to join it — each foot moves downward and away from the top, toes always pointing up the stairs; the hand stays on the rail; nobody speaks. Stylized 3D animation, exactly on model from the frame. No camera travel; nobody else; no cut; the feet never turn around or climb."
MOTION["P-02a"] = "From the hall floor looking up the flight, she looks down the stairs toward the lens, holds, then turns her face away to the side, her mouth closed the whole time — she never speaks or sings, her lips still; her hand stays on the newel, she stays seated on the top step; the staircase stays exactly as in the frame. Stylized 3D animation, exactly on model from the frame. No camera travel; nobody else; no cut; she never stands."
MOTION["P-05a"] = "The back of her right hand pushes the heap once across the table to its far edge — every bottle, sleeve and brace slides and stays on the table — then she sits back in the chair, shoulders dropping, her mouth closed and her lips still from the first frame to the last, she never speaks or sings, eyes on nothing past the lens, her left hand slack in her lap. Stylized 3D animation, exactly on model from the frame, every object rigid and present to the last frame. No camera travel; nobody else; no cut."
DUR.update({"P-01b": 4, "P-02a": 6, "P-01a": 5, "P-03b": 4, "P-05c": 3})
MOTION["P-05c"] = "At the window in profile, she looks out a moment longer, then her eyes drop to the sink and her shoulders settle; her hands stay on the sink's edge, her mouth closed the whole time — she never speaks or sings; the window, the curtain and the kitchen stay exactly as in the frame. Stylized 3D animation, exactly on model from the frame. No camera travel; nobody else; no cut; she never turns to the lens."
MOTION["P-02a"] = "From mid-flight looking up at the top step, she looks down the stairs toward the lens, holds, then turns her face away to the side, her mouth closed the whole time — she never speaks or sings; her hand stays on the newel, she stays seated on the top step; the staircase stays exactly as in the frame. Stylized 3D animation, exactly on model from the frame. No camera travel; nobody else; no cut; she never stands."
FIXN_IMG = {"P-01b": "the image was replaced on the user's Fixes (her own legs, from the side) → the first clip on the new frame; nobody speaks (§35A rule 6)", "P-03a": "the image was replaced on the user's Fixes (the P-03b brace copied onto her right knee) → the first clip on the new frame; nobody speaks (§35A rule 6)", "P-02a": "the image was replaced on the user's Fixes (a different angle, then her own staircase) → the first clip on the new frame; mouth closed, she never speaks (§35A rule 6)"}
MOTION["P-03a"] = "From the side at knee height, her right hand hauls the short brace's top strap up over the kneecap in one pull, holds a moment, and the brace sags back down below the kneecap as the hand eases; her left hand stays on the chair seat; she stays seated, nobody speaks; the chair, the slippers and the kitchen behind stay exactly as in the frame. Stylized 3D animation, exactly on model from the frame, the brace rigid in shape. No camera travel; nobody else; no cut; the brace never changes design."
MOTION["P-03b"] = "At floor level, she shifts her right foot once — the slipper slides a little forward on the floor and the brace around her ankle slumps with it, then the foot rests; her other foot and the chair stay exactly as in the frame; nobody speaks. Stylized 3D animation, exactly on model from the frame, the brace rigid in shape. No camera travel; nobody else; no cut; the brace never climbs back up the leg."
MOTION["P-01a_v3"] = "From the hall floor looking up the flight, she comes DOWN toward the lens, backwards: her right foot reaches back and lowers onto the step below, her weight follows it, the left foot joins it on that same step — she ends one step lower, a little larger in the frame, farther from the landing, both hands on the rail, her back to the lens; she never climbs, never rises toward the landing; nobody speaks. Stylized 3D animation, exactly on model from the frame. No camera travel; nobody else; no cut."
MOTION["P-01a_v4"] = "From the hall floor looking up the flight, she backs away from the landing: she retreats one step toward the lens, her right heel feeling for the step beneath her and settling there, her weight sinking onto it, the left foot joining it — she sinks lower in the frame and grows larger, her head dropping below the window, the landing above her staying empty; both hands slide down the rail with her, her back to the lens, her face to the landing; nobody speaks. Stylized 3D animation, exactly on model from the frame. No camera travel; nobody else; no cut; she never climbs, never steps onto the landing."
MOTION["P-01a_v5"] = "From the hall floor looking up the flight, she backs away from the landing slowly, one step at a time: her right heel feels for the step directly below the one it leaves and settles on it, her weight sinks onto it, the left foot joins it on that same step, and only then the next step begins — two slow steps in the whole clip, about two seconds each, every step taken in turn, each foot stopping at the next step; she sinks lower in the frame and grows larger, the landing above her staying empty, both hands sliding down the rail, her back to the lens, her face to the landing; nobody speaks. Stylized 3D animation, exactly on model from the frame. No camera travel; nobody else; no cut; she never climbs, never skips a step."
MOTION["P-01a"] = "From the hall floor looking up the flight, she takes exactly one slow step down backwards: her right foot lowers onto the step just below and takes her weight, the left foot joins it on that same step, and she holds there, both hands on the rail, her back to the lens, her face to the landing; nobody speaks. Stylized 3D animation, exactly on model from the frame, the staircase exactly as in the frame. No camera travel; nobody else; no cut; never a second step."
FIXN = {"P-03a": "the image was replaced on the user's Fix (a shorter brace, seated from the side) → the first clip on the new frame: one pull up, the brace sags back; nobody speaks",
        "P-01a": "user Fix: SHOULD NOT BE STEPPING SO FAR DOWN, IT SHOULD BE 1 STEP AT A TIME → one slow step only: the right foot to the step just below, the left joins it on that same step, then she holds; never a second step (§22X)",
        "P-01b": "user Fix: this should be stepping backwards → each foot moves down and away from the top, toes up the stairs, the feet never climb; nobody speaks (§35A rule 6)",
        "P-02a": "user: never talk the lyrics/script in B-roll → mouth closed, lips still, she never speaks or sings (§35A rule 6, HT25)",
        "P-05a_old": "user: make this into 3 brolls (the beat split; this clip re-cut to its own line) · §22X on v1: the heap vanished and her mouth moved → prompt: every object stays on the table to the last frame, mouth closed, she never speaks"}
MOTION["P-05c_v2"] = "Her lips stay sealed and her jaw still from the first frame to the last — a silent clip, she never speaks or sings; at the window in profile she looks out a moment longer, then only her eyes drop to the sink and her shoulders settle; her hands stay on the sink's edge; the window, the curtain and the kitchen stay exactly as in the frame. Stylized 3D animation, exactly on model from the frame. No camera travel; nobody else; no cut; she stays in profile."
FIXN["P-05c"] = "user Fix on v1: NO TALKING ABOUT THE MUSIC (her mouth opened and moved as if singing along) → the lips clause first and strongest: lips sealed, jaw still, a silent clip; only the eyes move (§22X, §35A rule 6)"
MOTION["P-05b"] = "In close on the open drawer, her hand pushes the drawer front once and the drawer slides shut until it jams on the stuffed sleeves and bottles inside, a sleeve cuff caught over its edge; the hand rests on the drawer front; the drawer, the cabinets and the counter stay exactly as in the frame; nobody speaks, nobody is in frame but the hand. Stylized 3D animation, exactly on model from the frame, every object rigid. No camera travel; nobody else; no cut; nothing new appears."
DUR["P-05b"] = 3
MOTION["P-03a_v4"] = "From the side at knee height, the short brace drifts slowly down her shin on its own — a little at a time, gravity taking it, the top strap easing off the kneecap and the whole brace settling lower, toward her ankle, by the last frame; her right hand lifts away from it, hovers, and rests on her thigh; her left hand stays on the chair seat; she stays seated, nobody speaks; the chair, the slippers and the kitchen behind stay exactly as in the frame. Stylized 3D animation, exactly on model from the frame, the brace rigid in shape. No camera travel; nobody else; no cut; the brace never climbs back up."
# every Fix note ever written on a beat stays in force for every later version (L18): the call lists them all
FIXALL = {"P-01a": ["v1: SHOULD NOT BE STEPPING SO FAR DOWN, IT SHOULD BE 1 STEP AT A TIME", "v2: SHOULD BE GOING BACK WARDS NOT UP", "v3: (never shown — climbed)", "v4: P01 SHOULD BE WALKING BACKWARDS SLOWLY ONE STEP AT A TIME NOT SKIPPING STEPS OF THE STAIRS"]}
fails = 0
for arg in sys.argv[1:]:
    parts = arg.split(":"); b, iv = parts[0], parts[1]; k = parts[2] if len(parts) > 2 else f"{b}@v2A"; cv = int(parts[3]) if len(parts) > 3 else 1; r = rows[b]
    if b == "P-05a": DUR[b] = r["duration"]
    mp = f"From this frame: {r['action']} — {r['pace']}; camera {r['camera']}"
    mo = MOTION["P-03a_v4"] if (b == "P-03a" and cv >= 4) else MOTION["P-05c_v2"] if (b == "P-05c" and cv >= 2) else MOTION["P-01a_v5"] if (b == "P-01a" and cv >= 5) else MOTION["P-01a_v4"] if (b == "P-01a" and cv >= 4) else MOTION["P-01a_v3"] if (b == "P-01a" and cv >= 3) else MOTION[b]
    if b == "P-01a" and cv >= 4: DUR[b] = 4
    if b == "P-01a" and cv >= 5: DUR[b] = 5
    pr = f'For the line "{r["line"]}": {mp}. {mo}'
    USERGO = {"P-05a": 'user 2026-10-01: "i want new ones on the brolls. i dont like these, you should never talk the lyrics/script in broll"'}
    if b in FIXN_IMG and cv >= 2: FIXN[b] = FIXN_IMG[b]
    GEN2 = {"P-03a": 4}   # the second generation on a replaced frame (the first was cv 3)
    if b == "P-01a" and cv >= 3:
        MOTION["P-01a"] = MOTION["P-01a_v3"]; USERGO["P-01a"] = 'user 2026-10-01: "FIX THOSE" on the board Fix "SHOULD BE GOING BACK WARDS NOT UP"'
        FIXN["P-01a"] = "user Fix: SHOULD BE GOING BACKWARDS NOT UP (v2 read as climbing) → the direction named three ways: down toward the lens, larger in the frame, farther from the landing; never climbs (§22X)"
    if b == "P-01a" and cv >= 5:
        USERGO["P-01a"] = 'user 2026-10-01: "P01 SHOULD BE WALKING BACKRWARDS SLOWLY ONE STEP AT A TIME NOT SKIPPING STEPS OF THE STAIRS"'
        FIXN["P-01a"] = "user Fix on v4 (she backed down about four steps, skipping some) → the pace named: slowly, one step at a time, each heel to the step directly below, both feet on it before the next, two steps in the whole clip, never a step skipped (§22X; the v1 note 'one step at a time' stays in force — L18)"
    elif b == "P-01a" and cv >= 4:
        USERGO["P-01a"] = 'user 2026-10-01: "I DONT NEED END FRAME IN P01" — the clip from the start frame alone, no pinned end frame'
        FIXN["P-01a"] = "§22X on v1–v3 (all three read her stance on the top step, facing the landing, as a climb) → the motion renamed as backing away / retreating from the landing: she sinks lower in the frame, her head drops below the window, the landing stays empty, hands slide down the rail; 4 s, one step; no end frame (user)"
    elif cv >= 3: FIXN[b] = "user: never talk the lyrics/script in B-roll (third generation on the user's own ask) → mouth closed and lips still first frame to last, she never speaks or sings (§35A rule 6, HT25)"
    if b == "P-03a" and cv >= 4:
        FIXN[b] = "user Fix on v3: IT SHOULD FEELING DRIFTING DOWN (v3 had her pull the brace up and it sagged back) → the motion rewritten: the brace drifts down her shin on its own, gravity taking it, her hand letting go; the act-map row's action and pace changed to match (§22X)"
    c = {"beat": b, "connector": "kling", "mode": 2, "kind": "broll", "prompt": pr, "duration": DUR[b], "resolution": "1080p", "aspect_ratio": "9:16",
         "start_image": urls[k], "start_approved": True, "pinned": False, "end_image": None, "end_approved": False, "script_line": r["line"], "motion_plan": mp,
         "motion_confirmed": True, "pace": r["pace"].split(",")[0], "subject_motion": "in_place", "prefer_multi_shots": "false", "generation": (2 if b in GEN2 and cv >= GEN2[b] else 1) if b in FIXN_IMG else cv, "user_go": USERGO.get(b) if cv >= 3 else None,
         "fix_note": FIXN.get(b) if cv > 1 else None, "fix_notes_all": FIXALL.get(b), "risk_class": "none", "pin_waived": None, "pilot": None, "taste": ["HT03", "HT04", "HT09", "HT12", "HT22"],
         "risks": [{"risk": "a second action or a loop", "prevented_by": "one movement named, then rest"}, {"risk": "off model", "prevented_by": "exactly on model from the frame"},
                   {"risk": "the camera travels", "prevented_by": "no camera travel, RV sway only"}],
         "note": f"clip v{cv} of this beat (from the confirmed image v{iv} {k[-1]}, job {jobs[k]})"}
    (H / f"{b}.v{cv}.call.json").write_text(json.dumps(c, indent=1, ensure_ascii=False)); (H / f"{b}.v{cv}.prompt.txt").write_text(pr)
    res = subprocess.run([sys.executable, str(PF), str(H / f"{b}.v{cv}.call.json")], capture_output=True, text=True)
    print(f"{b} clip: {len(pr)} chars {DUR[b]} s — {'PASS' if res.returncode == 0 else 'FAIL'}"); [print("   ", l) for l in res.stdout.splitlines() if "FAIL" in l]
    fails += res.returncode != 0
sys.exit(1 if fails else 0)
