import json, sys
sys.path.insert(0, '../../../products/stryde'); import stryde_product_sheet as s
F = lambda x: s.fill(x, 'right')
HEAD="Shot on an iPhone 17 Pro Max, handheld, the main 48MP Fusion camera at 24mm equivalent and f/1.78, left on its default 24 megapixel output, Smart HDR 5 and Deep Fusion on, Photographic Style on Standard, everything left on automatic — exposure, white balance and focus all chosen by the phone rather than by a person. An ordinary photo taken on an ordinary phone."
FILE="THIS IS A FILE, NOT A PICTURE. Nobody framed it, nobody lit it, nobody chose the moment and nobody looked at it afterwards. It is an unremarkable photograph off a phone. Sharpness is uneven across the frame: one plane is in focus and everything in front of and behind it falls away, because the lens has one fixed aperture and nobody chose where to put the focus. Edges are soft rather than crisp, with faint compression mush in the shadows and detail thinning toward the corners. Nothing has been sharpened, cleaned up, separated from its background or arranged, and no part of the frame has been given more attention than any other part."
GAIL="THE SAME WOMAN as in the attached reference sheet — broad square face, heavy jaw, a thin copper bob with the scalp showing at the parting, sixty-two, tall and big-boned —"
D1="Grey marl T-shirt, a faded lilac towelling dressing gown hanging open, navy cotton pyjama shorts above the knee, sheepskin slippers."
D2="A white broderie-anglaise short-sleeved blouse, wide-leg sage-green linen trousers rolled up above the knees, a thin gold watch."
AV="no posing for camera, no glancing at the lens, no staged or completed action, no centred composition, no stock footage look, no AI face, no extra fingers, no fused fingers, no deformed limbs, no warped background, no over-saturated colors, no moody dark grade, no light from nowhere, no lens flare, no readable text, no logos"
def P(scene, angle, focus, light, avoid):
    return "\n\n".join([HEAD, scene, "THE CAMERA ANGLE: "+angle+" This exact angle, not a straight-on eye-level view.", "FOCUS: "+focus+" The blur is optical: soft and round, never smeared.", light, FILE, "AVOID: "+avoid+", "+AV])+"\n"
HALL_L="THE LIGHT: the front-door glass behind the lens and the landing window at the top of the stairs light the hall, grey flat late-morning daylight, cool and even, the stair carpet soft in it. The shadows fall away from the door, one way only."
BED1="THE LIGHT: the window on the room's right-hand wall lights her from the right of the frame, grey flat late-morning daylight, cool, so she has a lit side toward the right and a softer shadow side. The shadows fall away from that source, one way only."
BED2="THE LIGHT: midday sun through the window on the room's right-hand wall, warmer now, a patch of sunlight on the carpet and a soft warm fill across the bed, so she has a lit side toward the right. The shadows fall away from the window, one way only."
PROD = s.REF_PROD
ANATH="Premium 3D anatomical visualisation for medical education, broadcast-quality CGI render, clean. Vertical composition. A stylised anatomical model of a single knee in true lateral profile, framed as a close-up from mid-thigh to mid-shin only, the patellar tendon two centimetres below the kneecap sitting just off-centre in the middle of the frame. Deep near-black field with a faint cool blue tint and very faint drifting particulate at depth. Full muscle stack in natural anatomical colour — quadriceps, hamstrings and calf, warm red and muted brick, semi-transparent and layered, broad directional grain along each belly, never individual fibres. The femur, patella and tibia deepest, warm ivory-gold with soft inner luminosity. The outer body contour a faint translucent glass-like shell, and a bright cool blue-white rim light tracing the silhouette, crisp against the black. Three-source render lighting, a cool pale-cyan key from upper left, a low warm amber bounce, strong falloff, volumetric scatter through the translucent tissue, clean satin sheen on the patellar tendon and bone."
ANEG="no text overlays, no labels, no numbers, no annotations, no arrows, no UI, no watermark, no opaque surfaces, no individual muscle fibres, no surface veins, no foot, no hip, no second leg, no whole body, no hands, no people, no clothing, no x-ray look, no flat illustration, no cartoon look, no vignette, no spotlight pool, no emission on the bone shafts, no glow at the tibial tuberosity, no glow on the shin bone, no lasers, no energy beams, no external energy"
B = {}
B["BR-032"] = P(GAIL+" IN THE SAME HOUSE as the attached hall photograph, on the staircase that rises away from the front door along the right-hand wall. She is halfway through coming down one stair towards the lens: her left hand gripping the banister rail hard, her left foot lowered onto the next stair, her right leg held stiff and straight behind on the stair above, the right knee braced, her weight leaning back onto the rail, her face tight with the effort, eyes on the step. "+D1,
 "the lens low, at the foot of the stairs, a little above the hall floor, looking up the flight at her from the front. Her whole figure on the stairs, the steps looming large nearest the lens.",
 "everything from near to far stays sharp — the steps, the rail, her, the landing behind.", HALL_L,
 "no both feet on one step, no running, no falling, no sitting on the stairs, no hand off the rail, no knee support, no product")
B["BR-033"] = P(GAIL+" IN THE SAME HOUSE as the attached hall photograph, on the staircase that rises away from the front door along the right-hand wall. Seen from behind, she is halfway through climbing one stair away from the lens, steady and easy: her right foot planted on the next stair up, her weight rising onto it, her left hand light on the banister rail, the dressing gown hem swinging behind her. "+D1,
 "the lens at her eye height from the hall floor, level, from directly behind her at the foot of the stairs. Her whole figure from head to slippers, the flight rising ahead of her to the landing window.",
 "everything from near to far stays sharp — her, the steps, the landing window.", HALL_L,
 "no face, no looking back at the lens, no stumbling, no hand gripping hard, no knee support, no product")
B["MECH-034"] = "\n\n".join([ANATH.replace("in true lateral profile,","in true lateral profile, the knee bent about thirty degrees as in stepping down off a stair, the leg reaching down in front,"),
 "One leg only, stepping down: the front of the thigh lengthening under tension to catch the body's weight as it lowers, the quadriceps drawn long and taut down to the kneecap, and that pull landing on the band of patellar tendon two centimetres below the kneecap.",
 "STATE — ALREADY UNDER LOAD AND ALREADY ACTIVE. The knee is already bent under load and the patellar tendon is already drawn taut. The emission is already established at the patellar tendon immediately below the patella, near-white at its core, mid-intensity and clearly glowing — not at peak, leaving headroom to escalate — warmth blooming a short way into the translucent layers around it. Unmistakably the brightest element in frame. The bones and the rest of the muscles stay calm by comparison.",
 s.ANAT_A_POINT_TIGHT, "AVOID: no straight leg, no walking pose, no stairs, "+ANEG])+"\n"
B["BR-035"] = P(GAIL+" IN THE SAME BEDROOM as the attached room photograph, sitting on the edge of the bed on the patchwork quilt. Both her hands are partway through peeling the plain black stretchy knee sleeve down off her right knee, the sleeve rolled down over itself to just below the kneecap, the skin of the knee pink and creased where it has been. "+D1,
 "the lens at her knee height, level, seen from three-quarter of her, close. Her hands, the sleeve and her right knee fill the frame, her dressing-gown hem and the quilt around, no face.",
 "her hands and the rolled sleeve are in sharp focus; the room behind falls to a soft, recognisable shape.", BED1,
 "no logo, no text on the sleeve, no brace, no strap, no product, no face")
B["MECH-036"] = "\n\n".join([ANATH.replace("in true lateral profile,","seen from the front, low, the lens a little below the knee looking up,").replace("the patellar tendon two centimetres below the kneecap sitting just off-centre in the middle of the frame","the kneecap and the band of patellar tendon below it filling the middle of the frame, the joint line just above it"),
 "One leg only, standing. A faint warm trace lies along the joint line where the thigh bone meets the shin bone, fading, and below it the band of patellar tendon two centimetres below the kneecap is where the light is gathering — the attention moving down from the joint line to the band underneath.",
 "STATE — ALREADY ACTIVE. The emission is already established at the patellar tendon immediately below the patella, near-white at its core, mid-intensity, the brightest element in frame; the joint line above it holds only a dim, fading warmth. The bones and muscles stay calm by comparison.",
 s.ANAT_A_POINT_TIGHT, "AVOID: no equal glow on the joint line and the band, no bright joint line, "+ANEG])+"\n"
B["PR-037"] = P("A woman's hand — sixty-two, broad, a thin gold watch on the wrist, the white broderie-anglaise cuff of a short sleeve — IN A SUNNY BEDROOM with pale blue walls, holds up the strap by the window. "+PROD+" held in a bottom-edge pinch: "+dict(s.HELD_GRIPS)["bottom-edge pinch"]+"; nothing rises above the shell's top edge, the peaks and notch clear against the window light, the wordmark facing the lens. "+s.SIZE_HELD,
 "the lens at the height of the strap, level, from the front, close. The hand and the strap fill the middle of the frame, the bright window soft behind.",
 "the strap's shell and wordmark are in sharp focus; the hand's wrist and the window fall soft.",
 "THE LIGHT: midday sun through the window behind and to the right, warm, rimming the shell's peaks and catching the chrome slides, a soft fill from the room on the front of the shell. The shadows fall towards the lens, one way only.",
 s.NEG_HELD_P+", "+F(s.NEG_WARP_P)+", no second strap, no worn strap, no face")
B["BR-038"] = P(GAIL+" IN THE SAME BEDROOM as the attached room photograph, sitting on the edge of the bed with her right leg stretched out straight in front of her, the heel on the carpet, sage trousers rolled above the knee. "+PROD+" "+F(s.PLACE_LOCK_C)+" "+s.SIZE_WORN+" "+s.FIT_SNUG+" "+s.LEG_SKIN+" "+D2,
 "the lens at her knee height, level, seen from three-quarter of her, close on the right knee and the strap, her hands resting on her thigh at the frame edge, no face.",
 "the strap and the kneecap are in sharp focus; the room behind falls to a soft, recognisable shape.", BED2,
 F(s.NEG_PLACE)+", no face")
B["BR-039"] = P("A woman's two hands — sixty-two, broad, a thin gold watch — IN A SUNNY BEDROOM with pale blue walls, hold the strap turned round, back to the lens. "+s.PAD_BACK_SHOT+" The fingertips are at the two ends of the shell, the band hanging slack below. "+s.SIZE_HELD,
 "the lens above, looking down into the inside of the shell, seen from the front, close. The inside of the shell fills the middle of the frame, the quilt soft below.",
 "the inner pad and the peaks are in sharp focus; the quilt below falls soft.", "THE LIGHT: midday sun from the window on the right, warm, raking across the matte pad so its curve reads. The shadows fall away from the window, one way only.",
 s.NEG_HELD_P+", "+F(s.NEG_WARP_P)+", no silicone look, no glossy pad, no blue pad, no markings on the pad, no wordmark on the inside, no face")
B["MECH-040"] = "\n\n".join([ANATH,
 "The product in place on this anatomical knee: "+PROD+" "+F(s.PLACE_LOCK_C),
 "Already fully and correctly in place per the placement above. Materials solid and opaque against the translucent anatomy, hardware catching bright hard specular flares, wordmark readable. The flexible band visibly tensions and the rigid shell presses into the tendon beneath it, deforming it slightly — the product is doing work, not resting on top.",
 "STATE — THE PAD HAS THE LOAD. The inside of the shell, the pad, is pressed against the patellar tendon and glows a clean cool pale blue where it takes the force, spreading that force across the shell; beneath it the patellar tendon immediately below the patella is cool and pale, only the last faint trace of warmth fading at its edges. The cool tone of the product is the brightest element in frame.",
 "AVOID: no hot spot under the strap, no orange glow at the site, no product floating off the tendon, no product on the kneecap, "+F(s.NEG_WARP_P)+", "+ANEG.replace("no clothing,","")])+"\n"
B["BR-041"] = P(GAIL+" IN THE SAME BEDROOM as the attached room photograph, sitting on the edge of the bed, her right leg straight out, the heel on the carpet, sage trousers rolled above the knee. "+PROD+" already closed on her leg but sitting clearly off-position at mid-shin, well below the knee; both her hands hold the shell by its two sides, palms and fingertips flat on the matte shell, about to slide it up. "+s.SIZE_WORN+" "+s.LEG_SKIN+" "+D2,
 "the lens at her knee height, level, in profile of the leg, close. From her mid-thigh to her ankle in frame, the strap at mid-shin in her hands, the bare kneecap above, no face.",
 "her hands and the strap are in sharp focus; the room behind falls soft.", BED2,
 "no strap at the knee yet, no strap on the kneecap, no band open, no band being threaded, no hand on the band, "+F(s.NEG_WARP_P)+", no face")
B["BR-042"] = P(GAIL+" IN THE SAME BEDROOM as the attached room photograph, sitting on the edge of the bed, her right leg straight, sage trousers rolled above the knee. "+PROD+" "+F(s.PLACE_LOCK_C)+" Her right forefinger rests on the shell's top edge in the notch, just touching the lower border of the kneecap, pointing to where it sits. "+s.SIZE_WORN+" "+s.LEG_SKIN+" "+D2,
 "the lens above, looking down at the right knee, seen from three-quarter of her, very close: the kneecap, the notch, her fingertip and the shell fill the frame.",
 "the fingertip and the notch are in sharp focus; the rest falls soft.", BED2,
 F(s.NEG_PLACE)+", no finger covering the notch, no face")
order=list(B)
for b,t in B.items(): open(f"{b}.txt","w").write(t); print(b,len(t))
json.dump(order,open("order.json","w"))
