# Act map beats. One row per shot. p = phrase ids carried; kind: SH spoken on camera, LS listener
# (line plays off-screen over this shot), SIL silent action, INS insert, MECH mechanism, CARD post type.
# fn = §30B function; vis = product visibility state; side: Margaret RIGHT, Barbara LEFT.
B = []
def b(id, p, kind, scale, rig, fn, subj, emo, vis="—", note=""):
    B.append(dict(id=id, p=p, kind=kind, scale=scale, rig=rig, fn=fn, subj=subj, emo=emo, vis=vis, note=note))

# ---------------- HOOK A · "Get away" · stairs + hall · story day HKA
b("HKA-SC01-SH01","H-A0","SIL","ECU","F3","CONSEQUENCE","Margaret's right knee trembling as she lowers backwards onto the next tread, same foot leading","dread","—","cool grey grade; step-to gait")
b("HKA-SC01-SH02","H-A0","INS","INSERT","F2","CONSEQUENCE","Knuckles white on the dark-wood banister rail","strain")
b("HKA-SC01-SH03","H-A1","SH","FULL","F5","CONSEQUENCE","Sarah in the hall, shopping bags drop, she runs for the stairs — 'Mom! Your knee! Here, let me help you.'","alarm","—","bags hit the hall carpet; §27E consequence")
b("HKA-SC01-SH04","H-A2","SH","CU","F3","CONSEQUENCE","Margaret yanks her arm out of Sarah's hand — 'No! I can do this. Get away from me!'","shame masked as anger")
b("HKA-SC01-SH05","H-A2","LS","MCU","F2","CONSEQUENCE","Sarah freezes, hand still raised","hurt")
b("HKA-SC01-SH06","H-A3","SH","MCU","F1","CONSEQUENCE","Sarah, quietly — 'Mom, you're going down backwards.'","grief")
b("HKA-SC01-SH07","H-A4","SH","CU","F1","CONSEQUENCE","Margaret turns her face to the wall, chin shaking — 'I know. Please don't watch me.'","shame","—","open loop planted: backwards on the stairs")
b("HKA-SC01-SH08","—","CARD","—","—","—","Black card, white type: 6 weeks ago","—","—","post type §17")
# ---------------- HOOK B · "Seventy-one!" · station staircase · story day HKB (after-state, flash-forward)
b("HKB-SC01-SH01","H-B0","SIL","WIDE","F4","CONTRAST","Busy station staircase at rush hour, rails both sides and one down the middle","bustle","—","warm bright grade — the film's AF look")
b("HKB-SC01-SH02","H-B1,H-B2","SH","MCU","F2","CONSEQUENCE","Two women (late 40s) gripping side rails, stiff-kneed, one step at a time — 'My knees hate these stairs.' / 'Tell me about it.'","weary","—","one-off subjects W1, W2")
b("HKB-SC01-SH03","H-B3","SH","FULL","F5","CONTRAST","Margaret (lanyard, handbag) comes down the middle almost running, hand skimming the centre rail — 'Excuse me! Sorry, love, I'm late for work!'","brisk joy","CONCEALED","see decision D4: hem")
b("HKB-SC01-SH04","H-B3","INS","ECU","F4","CONTRAST","Her knees moving easily, reciprocal gait, under the cropped trouser hem","ease","CONCEALED","D4: scripted 'strap shows below a cropped hem' is not physically possible")
b("HKB-SC01-SH05","H-B4","SH","MCU","F1","CONTRAST","Both heads turn; Woman 1 staring after her — 'She's got to be seventy!'","disbelief")
b("HKB-SC01-SH06","H-B5","SH","WIDE","F2","CONTRAST","From the bottom, not looking back — 'Seventy-one!' — and she's gone into the crowd","triumph")
b("HKB-SC01-SH07","—","CARD","—","—","—","Black card, white type: 6 weeks ago","—","—","post type")
# ---------------- HOOK C · The floor · kitchen · story day HKC
b("HKC-SC01-SH01","H-C0","INS","CU","F2","CONSEQUENCE","A mug slides off the counter edge and breaks on the vinyl floor","jolt","—","§27E material failure")
b("HKC-SC01-SH02","H-C0","SIL","MEDIUM","F3","CONSEQUENCE","Margaret bends for it","effort")
b("HKC-SC01-SH03","H-C1","SH","ECU","F3","CONSEQUENCE","Her right knee buckles sideways, she shouts as she drops — 'Frank! Frank, it's my knee!'","pain","—","D5: 'sideways' contradicts P-027")
b("HKC-SC01-SH04","H-C2","SH","FULL","F3","CONSEQUENCE","Frank gets down slowly, arm under hers — 'I've got you. Give me your arm.'","fear held")
b("HKC-SC01-SH05","H-C3","SH","CU","F3","CONSEQUENCE","His arms shake; she doesn't move — 'Stop, Frank. You'll hurt your back.'","fear for him")
b("HKC-SC01-SH06","H-C4","SH","CU","F1","CONSEQUENCE","'I'm not leaving you on the floor.'","stubborn love")
b("HKC-SC01-SH07","—","SIL","WIDE","F2","CONSEQUENCE","The two of them sitting on the floor, backs against the cupboards, broken mug between their feet","defeat","—","hold 2s, then card")
b("HKC-SC01-SH08","—","CARD","—","—","—","Black card, white type: 6 weeks ago","—","—","post type")

# ---------------- BF · SC02 · Kitchen · afternoon · story day D1
b("BF-SC02-SH01","A","SIL","INSERT","F4","ILLUSTRATE","A stairlift brochure slid across the floral oilcloth table","pressure","—","brochure: generic, no readable brand (§17)")
b("BF-SC02-SH02","P-001","SH","MCU","F2","—","Sarah — 'It's just a stairlift, Mom. Just look at it.'","pleading")
b("BF-SC02-SH03","P-002","SH","CU","F2","—","Margaret, not looking at it — 'I know what it is.'","closed")
b("BF-SC02-SH04","P-003","SH","MCU","F3","—","Sarah — 'I watched you come down those stairs backwards.'","hurt")
b("BF-SC02-SH05","P-004","SH","CU","F2","—","Margaret — 'Then don't watch.'","cold shame")
b("BF-SC02-SH06","P-005","SH","CU","F1","—","Sarah, voice cracking — 'Somebody has to. You're 71...'","crack")
b("BF-SC02-SH07","P-005","INS","INSERT","F2","CONSEQUENCE","Cutaway on 'tea up on a tray': the tray waiting on the counter, one cup, one saucer","life shrunk","—","CONSEQUENCE for an abstract line")
b("BF-SC02-SH08","P-006","SH","CU","F1","—","Margaret — 'I've done the physio, Sarah. The painkillers. The injections...'","tired defiance")
b("BF-SC02-SH09","P-006","INS","INSERT","F2","CONSEQUENCE","Bedroom: the open drawer of braces (bedroom plate prop), a flesh-toned sleeve lying slack","failed fixes","—","plants the drawer; no competitor wordmarks (§10)")
b("BF-SC02-SH10","P-007","SH","MCU","F2","—","Sarah — 'So let them put the stairlift in.'","pushing")
b("BF-SC02-SH11","P-008","SH","CU","F1","—","Margaret — 'A stairlift is how it starts.'","fear")
b("BF-SC02-SH12","P-009","SH","MCU","F2","—","Sarah — 'How what starts?'","confused")
b("BF-SC02-SH13","A","SIL","CU","F1","—","Margaret doesn't answer; eyes to the hall door and the stairs beyond","unresolved","—","scene ends unresolved (§3B)")
# ---------------- BF · SC03 · Bedroom · night · D1 (nightwear)
b("BF-SC03-SH01","A","SIL","WIDE","F2","—","Dark bedroom, streetlight through the net curtain, two shapes in bed","still")
b("BF-SC03-SH02","P-010","SH","MCU","F2","—","Frank on his back in the dark — 'Do you ever think about which one of us goes first?'","quiet dread")
b("BF-SC03-SH03","P-011","SH","CU","F2","—","Margaret — 'Frank.'","warning")
b("BF-SC03-SH04","P-012","SH","MCU","F1","—","Frank — 'If it's me... who gets you down the stairs?'","fear")
b("BF-SC03-SH05","A","SIL","CU","F2","—","A long silence; the bedside clock, the blister pack by her glasses","held breath","—","designed silence 2–3s")
b("BF-SC03-SH06","P-013","SH","CU","F2","—","Margaret — 'Go to sleep, love.'","masking")
b("BF-SC03-SH07","A","SIL","CU","F1","—","She lies there with her eyes open","unresolved")
# ---------------- PB · SC04 · Wedding reception · golden hour → fairy lights · D2
b("PB-SC04-SH01","A","SIL","WIDE","F4","—","Reception room, dance floor full, fairy lights, Margaret seated at a round table","celebration around stillness")
b("PB-SC04-SH02","P-014","SH","MCU","F2","CONSEQUENCE","Emily in her wedding dress, hands held out — 'Grandma, you promised...'","hopeful")
b("PB-SC04-SH03","P-015","SH","CU","F1","CONSEQUENCE","Margaret smiling, eyes wet — 'I know I did, sweetheart. I'll watch from here.'","grief behind a smile")
b("PB-SC04-SH04","A","SIL","MCU","F2","CONSEQUENCE","Emily's smile drops; she goes back to the floor","deflated")
b("PB-SC04-SH05","A","SIL","FULL","F4","CONTRAST","On the floor, a woman in her seventies (Barbara) dancing like she's forty","joy","CONCEALED","Barbara's strap hidden under the dress — §9: product absent until the Turn")
b("PB-SC04-SH06","P-016","SH","MCU","F2","—","Frank — 'Is that Barbara out there? Your cousin Barbara?'","surprised")
b("PB-SC04-SH07","P-017","SH","CU","F2","—","Margaret — 'She's 74.'","flat")
b("PB-SC04-SH08","P-018","SH","MCU","F2","—","Frank — 'I thought her knees were bone on bone.'","puzzled")
b("PB-SC04-SH09","P-019","SH","CU","F1","—","Margaret, watching her — 'They are. I always thought hers weren't as bad as mine.'","envy, dawning","—","open loop: what is Barbara doing?")
# ---------------- PB→TN · SC05 · Kitchen · morning a week later · D3
b("PB-SC05-SH01","A","INS","INSERT","F4","CONSEQUENCE","The morning ritual lined up on the table: two pills, a tube of gel, a knee brace, an ice pack","routine","—","generic blank packaging")
b("PB-SC05-SH02","P-020","SH","MCU","F2","—","Barbara, mug in hand — 'You've done this every morning since I got here...'","gentle probe")
b("PB-SC05-SH03","P-021","SH","CU","F2","CONSEQUENCE","Margaret — 'For eleven years.'","resigned")
b("TN-SC05-SH04","P-022","SH","MCU","F1","—","Barbara — 'Can I show you something?'","decision")
b("TN-SC05-SH05","A","INS","ECU","F4","PRODUCT-IN-LIFE","REVEAL: Barbara pulls up her wide trouser leg; the strap sits under her left kneecap","reveal","REVEAL","hero insert §24G; nano_banana_pro; PLACE-LOCK; D3 'small' not rendered small")
b("TN-SC05-SH06","P-023","SH","MCU","F2","—","Barbara — 'It's called Stryde. I had it on at the wedding. All night.'","proud")
b("TN-SC05-SH07","P-024","SH","CU","F2","—","Margaret — 'That little thing? ...can't possibly work on knees like mine.'","scepticism")
b("TN-SC05-SH08","P-025","SH","MCU","F1","—","Barbara — 'That's exactly what I said. Last winter I was sleeping on my sofa...'","candour")
b("TN-SC05-SH09","P-026","SH","MCU","F2","—","Barbara — 'Every brace you've ever bought was made to keep you comfortable while your knee got worse...'","conviction")
b("TN-SC05-SH10","P-026","INS","INSERT","F4","EVIDENCE","On 'a sleeve just squeezes / a brace just stops it going sideways': Barbara's hand turns the old hinged brace on the table","demonstration","—","no competitor wordmark")
b("TN-SC05-SH11","P-027","SH","CU","F2","—","Margaret — 'No.'","listening")
b("TN-SC05-SH12","P-028","SH","MCU","F2","—","Barbara — 'It hurts coming down the stairs. Put your finger just under your kneecap...'","guiding")
b("TN-SC05-SH13","P-028,P-029","INS","ECU","F2","EVIDENCE","Margaret's own finger pressing into the tendon just under her right kneecap — 'Yes.'","recognition","—","demonstration gate: verifiable in 3s")
b("TN-SC05-SH14","P-030","SH","MCU","F1","—","Barbara — 'That's the tendon. Every step you take lands right there...'","weight")
b("TN-SC05-SH15","P-030","MECH","SCREEN","F1","MECHANISM","Barbara turns her phone: the knee render; push in and cut on the push to the §12A render — load arriving at the tendon at footstep rate","understanding","—","SCREEN route (§24G); 17× is Tier 3 — no numerals on screen")
b("TN-SC05-SH16","P-031","SH","CU","F2","—","Margaret — 'Barbara, my knees are bone on bone. There's nothing left in there.'","despair")
b("TN-SC05-SH17","P-032","SH","CU","F1","—","Barbara — 'Mine too. This doesn't put anything back... I haven't got time to lie to you.'","hard honesty","—","trust line; hold on the eyes")
b("TN-SC05-SH18","P-033","SH","CU","F2","—","Margaret — 'Then what does it do?'","opening")
b("TN-SC05-SH19","P-034","SH","MCU","F2","—","Barbara — 'It changes where the weight lands. It sits just under the kneecap...'","explaining","REVEAL","D1 load-path vs Product Sheet 'protection'; D2 'silicone pad'")
b("TN-SC05-SH20","P-034","MECH","INSIDE","F1","MECHANISM","§12A anatomical render: the shell seated on the tendon at walking cadence, load met at the shell","clarity","—","INSIDE allowed after SCREEN (SH15); never renders a silicone pad")
b("TN-SC05-SH21","P-035","SH","MCU","F2","—","Barbara — 'They measured it. Thirty four percent less strain, every step.'","certainty","—","Tier 3 — generate as scripted; any on-screen numeral is post")
b("TN-SC05-SH22","P-036","MECH","INSIDE","F1","MECHANISM","Render: worn cartilage and the spot taking the weight; every other treatment aimed at the whole joint","insight","—","Tier 3 breadth claim — flagged")
b("TN-SC05-SH23","P-036","SH","MCU","F1","—","Barbara — '...That's why nothing worked.'","landing")
b("TN-SC05-SH24","P-037","SH","CU","F2","—","Barbara — 'Your arthritis will still be there. The weight just won't be landing where it hurts.'","gentle")
b("TN-SC05-SH25","P-038","SH","CU","F2","—","Margaret — 'It'll slip. They all slip.'","objection")
b("TN-SC05-SH26","P-039","SH","MCU","F2","—","Barbara — 'It's adjustable, and it doesn't go over the joint...'","patient")
b("TN-SC05-SH27","P-039","INS","INSERT","F4","EVIDENCE","§9B seating beat on 'Ten seconds to put on': Barbara stands, leg straight, and slides the closed strap up from mid-shin in one move until the kneecap's lower pole seats in the notch","ease","VISIBLE","SEAT-LOCK, straight leg (Product Sheet ruling); Barbara's left leg; nano_banana_pro")
b("TN-SC05-SH28","P-040","SH","CU","F1","—","Margaret, quietly — 'I can't try another thing that doesn't work... I can't get my hopes up again.'","raw")
b("TN-SC05-SH29","P-041","SH","MCU","F2","—","Barbara, putting a strap in her hand — 'Then don't get your hopes up. Just put it on...'","dry kindness")
b("TN-SC05-SH30","P-041","INS","INSERT","F2","PRODUCT-IN-LIFE","The strap placed in Margaret's palm, chrome slides catching the window","threshold","HELD","§9A held beat; nano_banana_pro")
b("TN-SC05-SH31","P-041","SH","CU","F2","—","'...And keep your hand on the rail. I'm not crazy.' — Margaret almost smiles","a crack of hope","—","ends unresolved: will she?")
# ---------------- TN · SC06 · Stairs · late morning · D3 (continuous day)
b("TN-SC06-SH01","A","SIL","WIDE","F2","CONTRAST","From the hall looking up: Margaret at the top gripping the brass-capped newel post; Barbara at the bottom","fear","VISIBLE","right trouser leg drawn up above the knee and staying there, as WEAR-REVEAL leaves it; mirrors Hook A's axis")
b("TN-SC06-SH02","P-042","SH","MCU","F2","—","Margaret — 'I can't, Barbara. I haven't come down these forwards in two years.'","terror")
b("TN-SC06-SH03","P-043","SH","MCU","F2","—","Barbara — 'Hand on the rail. One step. That's all I'm asking.'","steady")
b("TN-SC06-SH04","A","SIL","ECU","F2","CONTRAST","The first step, forwards. Slowly. The right knee takes the weight — strap on the tendon, band tensioning","braced","VISIBLE","§12B tension cycle; mirror of HKA-SH01")
b("TN-SC06-SH05","P-044","SH","MCU","F1","—","Barbara — 'Feel that under the kneecap? That's the weight going somewhere else.'","coaching")
b("TN-SC06-SH06","A","SIL","FULL","F2","CONTRAST","Second step. Third. Uncut. Her eyes fill","disbelief","VISIBLE","demonstration plays uncut (§30B)")
b("TN-SC06-SH07","P-045","SH","CU","F1","CONTRAST","Margaret, tears running — 'Barbara... I'm not gripping it.'","wonder")
b("TN-SC06-SH08","A","INS","INSERT","F2","CONTRAST","Her hand resting open on the rail, not gripping it","release","—","mirror of HKA-SH02 white knuckles; D14")
b("TN-SC06-SH09","P-046","SH","CU","F1","—","Barbara, own eyes wet — 'I know, love. Keep coming.'","moved")
b("TN-SC06-SH10","A","SIL","FULL","F5","CONTRAST","She comes the rest of the way down. Both feet. Forwards. Reciprocal gait","breakthrough","VISIBLE","after-state gait (§30D)")
b("TN-SC06-SH11","P-047","SH","CU","F2","—","At the bottom, hand over her mouth, weeping — 'I can't believe it. I can't believe it.'","release")
b("TN-SC06-SH12","A","SIL","MEDIUM","F2","—","Barbara holds her","comfort")
b("TN-SC06-SH13","P-048","SH","MCU","F2","—","Barbara — 'Well, don't just stand there. Put the kettle on.' Margaret laughs through tears","relief","—","callback to 'tea on a tray' (SC02)")
# ---------------- AF · SC07 · Doctor's office · midday · D4
b("AF-SC07-SH00","—","CARD","—","—","—","Time card: A month later","—","—","post type (optional — decision D8)")
b("AF-SC07-SH01","A","SIL","WIDE","F2","CONTRAST","Margaret walks in and sits unaided; the doctor at his desk, X-ray on the monitor","ease","CONCEALED")
b("AF-SC07-SH02","P-049","SH","MCU","F2","—","Doctor, looking at the X-ray — 'Your new X-ray looks exactly like the old one, Margaret. Bone on bone, both knees.'","clinical","—","X-ray: no readable numerals; plate shows 'L' — D9")
b("AF-SC07-SH03","P-050","SH","CU","F2","—","Margaret — 'I know.'","quiet pride")
b("AF-SC07-SH04","P-051","SH","MCU","F1","—","Doctor — 'So how did you just walk in here like that?'","curious")
b("AF-SC07-SH05","A","INS","ECU","F4","PRODUCT-IN-LIFE","Margaret pulls up her trouser leg: the strap under her right kneecap","reveal","REVEAL","nano_banana_pro; PLACE-LOCK-C (bent knee)")
b("AF-SC07-SH06","P-052","SH","MCU","F1","—","Doctor, leaning in, nodding — 'That makes sense. It's moving the weight off the worn part. Keep wearing it.'","approval","REVEAL","§19B permitted; mechanism wording = D1")
b("AF-SC07-SH07","P-053","SH","CU","F2","—","Margaret, smiling — 'I wasn't planning on taking it off.'","wry")
# ---------------- AF · SC08 · Hall / front door · late afternoon · D5
b("AF-SC08-SH01","A","SIL","FULL","F5","CONTRAST","Front door opens; Margaret in with two bags of shopping; Frank in the hall, coat half on","brisk / worried","CONCEALED","mirror of HKA: bags now carried in, not dropped")
b("AF-SC08-SH02","P-054","SH","MCU","F2","—","Frank — 'I was just coming to look for you. You were gone a long time.'","worry")
b("AF-SC08-SH03","P-055","SH","CU","F2","—","Margaret — 'I know.'","calm")
b("AF-SC08-SH04","P-056","SH","MCU","F2","—","Frank — 'Where did you go?'","puzzled")
b("AF-SC08-SH05","P-057","SH","CU","F2","—","Margaret — 'Into town.'","matter-of-fact")
b("AF-SC08-SH06","P-058","SH","MCU","F1","—","Frank — 'You walked into town? That's two miles.'","astonished")
b("AF-SC08-SH07","P-059","SH","CU","F2","CONTRAST","Margaret, putting the bags down — 'Each way.'","quiet triumph")
b("AF-SC08-SH08","A","SIL","CU","F1","—","Frank looks at her for a long moment","dawning")
b("AF-SC08-SH09","P-060","SH","MCU","F2","—","Frank — 'I called the stairlift man.'","confession")
b("AF-SC08-SH10","P-061","SH","CU","F2","—","Margaret — 'Frank...'","bracing")
b("AF-SC08-SH11","P-062","SH","CU","F1","—","Frank — 'I told him not to come.' (voice goes) 'All those nights I lay there thinking...'","breaking","—","pays SC03")
b("AF-SC08-SH12","P-063","SH","TWO-SHOT","F2","CONTRAST","Margaret takes his hand — 'Then I'll manage the stairs.'","tender resolve","—","pays 'who gets you down the stairs?'")
# ---------------- AF · SC09 · Stairs · Sunday midday · D6
b("AF-SC09-SH00","—","CARD","—","—","—","Time card: Sunday","—","—","post type (optional — D8)")
b("AF-SC09-SH01","A","SIL","FULL","F5","CONTRAST","From the hall: Margaret going up forwards at a normal pace; Sarah behind her, arms out","protective","CONCEALED","D6: 'hand resting on the rail' vs Product Sheet after-state")
b("AF-SC09-SH02","P-064","SH","MCU","F2","—","Sarah — 'Slowly, Mom. I'm right behind you.'","habit")
b("AF-SC09-SH03","A","SIL","ECU","F4","CONTRAST","Margaret's feet, reciprocal gait up the brass-rodded treads","ease","CONCEALED","mirror of HKA-SH01")
b("AF-SC09-SH04","P-065","SH","MCU","F2","CONTRAST","At the top, she turns — 'You can put your arms down now, love.'","gentle mischief")
b("AF-SC09-SH05","A","SIL","MEDIUM","F1","CONTRAST","Sarah halfway up, arms still out; slowly lowers them","stunned")
b("AF-SC09-SH06","P-066","SH","CU","F1","—","Sarah, tearing up — 'Mom... when did that happen?'","wonder")
b("AF-SC09-SH07","P-067","SH","CU","F2","—","Margaret — 'Six weeks ago. Barbara happened.'","warm","—","title payoff")
b("AF-SC09-SH08","P-068","SH","MCU","F2","—","Sarah — 'What does that even mean?'","laughing confusion")
b("AF-SC09-SH09","P-069","INS","ECU","F4","PRODUCT-IN-LIFE","Margaret pulls up her trouser leg on the top step: the strap under her right kneecap","show","REVEAL","nano_banana_pro")
b("AF-SC09-SH10","P-069","SH","MCU","F2","—","'It sits on the tendon under my kneecap... because the weight isn't landing where it hurts.'","assured","REVEAL","D1 wording")
# ---------------- AF · SC10 · Kitchen · Sunday afternoon · D6 (same day)
b("AF-SC10-SH01","A","SIL","INSERT","F2","—","Later. The kitchen radio on the windowsill, music playing","warmth","—","TIME CUT, same day")
b("AF-SC10-SH02","P-070","SH","MCU","F2","—","Emily — 'Grandma. You still owe me a dance.'","playful","—","mirror of SC04")
b("AF-SC10-SH03","P-071","SH","CU","F1","CONTRAST","Margaret — 'I always keep my promises.'","joy")
b("AF-SC10-SH04","A","SIL","FULL","F4","CONTRAST","Margaret takes her hands; they dance slowly around the kitchen, Margaret in her slippers","joy","CONCEALED","uncut; pays the wedding")
b("AF-SC10-SH05","A","SIL","MCU","F1","—","Sarah in the doorway, laughing and crying at once","overflow")
# ---------------- OC · SC11 · Living room · afternoon · D7
b("OC-SC11-SH01","P-072","SH","MCU","F2","—","Margaret in the armchair, phone to her ear — 'Joan, it's me. I've found something for your knees.'","purpose")
b("OC-SC11-SH02","P-073","LS","CU","F2","—","Joan off-screen, phone-filtered — 'Oh, Margaret. Not another one.'","—","—","Joan voice-only (decision D7)")
b("OC-SC11-SH03","P-074","SH","MCU","F1","—","'That's exactly what I said. It's called Stryde. Barbara gave me one...'","conviction","—","offer lines: BOGO, 60 days — unconfirmed, generate as scripted")
b("OC-SC11-SH04","P-074","INS","INSERT","F4","EVIDENCE","On 'you keep the straps': two straps in hand, turned through the window light","quality","HELD","§30B quality demo; nano_banana_pro")
b("OC-SC11-SH05","P-075","LS","CU","F2","—","Joan off-screen — 'Well. What have I got to lose?'","—")
b("OC-SC11-SH06","P-076","SH","CU","F1","—","Margaret — 'Nothing. Come over on Sunday. You're walking up my stairs on your own.'","warm certainty","—","last line; ends at rest")
# ---------------- OC · SC12 · Product end card
b("OC-SC12-SH01","—","INS","INSERT","F4","EVIDENCE","End card: two units and the packaging on a clean sweep, the film's LUT; offer and guarantee in post type","trust","HELD","§24G end card; nano_banana_pro or Sunburst (no person)")
