import sys; sys.path.insert(0,'.')
from data import LOOK_STRING
VOICE_JOAN = ("A woman of seventy-three, Lincolnshire, a thin reedy nasal head voice, and a slow heavy drawl that sags at every line end. "
 "Flat Lincolnshire vowels, no RP, nothing southern. Dry, little breath on the tone, a slight nasal edge. "
 "Slow, long vowels, a short pause before she turns a thought. Lines trail off downwards. Soft, lazy consonants and dropped h's. "
 "Held vowels waver and the breath runs short on longer lines. Emphasis is a stretched vowel on the key word, never louder. "
 "A small reluctant laugh through the nose.")
SEED = ("Photographed as a single frame from a feature film, shot on a large-format digital cinema camera with spherical prime lenses at 50mm and T2.0, "
 "the camera on a locked tripod and operated by a camera crew who framed and lit this moment on purpose. A still lifted from the finished film, "
 "not a photograph and not a phone video, composed natively for a vertical 9:16 frame with no letterbox bars. "
 "The frame is composed by a camera operator. The subject is placed deliberately off-centre, with looking room in the direction they face and headroom set for the shot size. "
 "The room is arranged in depth behind them, and no edge of the frame cuts the body at a joint. The person never fills the frame edge to edge: this is a medium close-up, "
 "and the person takes up head and chest, with the room readable to one side as part of the composition. "
 "Joan, a woman of seventy-three from Lincolnshire, sits at the small table in her own narrow terraced-house kitchen. She is wiry and small, with a narrow bony face, "
 "high cheekbones, a thin mouth and pale grey eyes; fine thinning grey hair pinned back with scalp showing at the parting; reading glasses pushed up onto her head; "
 "a beige hearing aid behind her right ear. She wears a sage-green quilted gilet over a faded blue check shirt. She sits upright with her forearms on the table, "
 "looking off-lens to camera-left at a friend across the table, mouth closed, about to speak. Behind her, soft and out of focus, pale blue painted cupboards, "
 "a kettle and a wall calendar. "
 "EVERY PERSON IN FRAME IS ANATOMICALLY WHOLE. Each person has exactly one head attached to one neck, two arms and two legs, each joined to the body at the right place "
 "and bending only at real joints. Every visible hand has one thumb and four fingers, separate, correctly sized, gripping or resting the way a real hand does. "
 "Any part of a body that is not visible is out of view for a reason you can see — cut by the frame edge or hidden behind a named object — never simply missing inside the frame. "
 "The face holds exactly where Joan is at this moment: settled and ordinary, jaw relaxed, eyes resting on her friend, brow easy, breathing steadily. "
 "Not a neutral face and not a posed expression, but a person in the middle of an ordinary conversation. "
 "Skin rendered in literal detail at near-macro fidelity, nothing softened: deep crow's feet, fine vertical lines above the lip, thin papery skin at the temples and a few age spots "
 "across the cheekbones, visible pores across the nose, forehead and cheeks, uneven in size and clearly individually resolved, fine vellus hair catching the key light along the jawline, "
 "natural oil sheen breaking the specular into separated micro-highlights on the T-zone while the cheeks sit matte and slightly rough, faint subsurface redness at the nostrils, "
 "ear rims and under the eyes, mildly uneven tone between forehead, cheeks and neck, dry texture on the lips with fine vertical lines. The key light rakes across the face so every line, "
 "pore and hair casts its own tiny shadow. Highlights break up at pore level, never sweeping smooth. "
 "THE LIGHT IS A LIT SET, MOTIVATED BY THE KITCHEN WINDOW ON CAMERA-LEFT. The key is soft daylight, raised slightly above the eye line, at a key-to-fill ratio of about 2:1, "
 "so every face has a lit side and a shadow side and the transition between them falls across the near cheek. A fill from the opposite side holds detail in the shadow. "
 "A faint edge light from behind separates the head and shoulders from the background. The background is lit only by its own practicals and spill. "
 "Every light in frame has a source you could point to. "
 + LOOK_STRING + " "
 "Weight and support everywhere: body load visibly on one foot or braced hand, fabric hanging from contact points and creasing at joints, every object resting on something "
 "with a tight contact shadow, soft deforming under hard, liquids level with gravity, nothing floating. "
 "This is a frame from a real film shoot, not a render. Real lens optics: focus falls off gradually either side of one chosen plane, and the out-of-focus areas are soft and round "
 "rather than smeared. Highlights behave the way a cinema sensor handles them, rolling off softly with a faint halation around the window. Shadows hold detail rather than being lifted "
 "flat by phone processing. No digital sharpening, no HDR tone-mapping, no phone processing, no beauty retouch, no diffusion glow on skin. Under the grade, skin, fabric and surfaces "
 "keep all of their real texture. "
 "Avoid: no phone camera look, no smartphone processing, no HDR tone-mapping, no flat lifted shadows, no over-sharpening halos, no selfie framing, no digital video look, no CGI look, "
 "no plastic skin, no beauty retouch, no diffusion filter glow on skin, no flat frontal key, no unmotivated light, no letterbox bars, no generated film grain, no stock footage look, "
 "no commercial gloss, no perfect symmetrical face, no actor looking into the lens, no poreless skin, no airbrushed skin, no glowing radiant skin, no youthful skin, "
 "no generically pleasant symmetrical face, no default silver swept-back hair, no stock retiree archetype, no missing or extra fingers, no malformed hands, no text, no phone in her hand.")
SEEDANCE = ("INGREDIENTS. @image1 is the opening composition: the clip opens on exactly this framing, light and camera position, and nothing in it is re-composed. "
 "@image1 is also Joan: her face, age, hair, build and clothes. There are no other ingredients. One continuous shot with no cuts. "
 "Joan sits at her kitchen table talking to a friend just off frame to camera-left. She takes a small breath, then says: \"Oh, Margaret. Not another one.\" "
 "She pauses for a beat, glances down at the table and back up, and says: \"Well. What have I got to lose?\" After the last word her mouth closes and she holds the look. "
 + VOICE_JOAN + " "
 "This clip is her voice reference, so both lines are read plainly at her natural pace: no emotional colouring, no sigh, no laugh, the same level from first word to last. "
 "Audio is clean production sound from a boom microphone just out of frame above the speaker: close, clear and even, with a little of the room's natural tone behind the voice. "
 "Breath and mouth detail are present but never exaggerated. No phone-microphone proximity, no compression pumping, no music under the dialogue. "
 "A small terraced kitchen with hard painted cupboard doors; short dry reflections with almost no tail; her voice close to the microphone with a little room in the signal. "
 "One gesture only: on 'What have I got to lose?' her right hand turns palm-up on the table and settles. Her eyes stay on her friend except the one glance down and back. "
 "Steam drifts from a mug at the edge of the frame. "
 "Camera on a tripod, framed and locked, with no drift, no sway and no reframe. The only camera life is one small operator pan or tilt of a few degrees to keep the subject in frame "
 "as they shift. It arrives a beat late and corrects only part of the way. The subject and the room carry all the other movement. "
 "The look exactly as in the start frame: same lens, same depth of field, same grade, same light direction and same optical texture. Nothing about the look changes across the clip. "
 "24 frames per second, with natural motion blur on moving hands and objects. "
 "Avoid: no cuts, no second shot, no music, no background music bed, no second voice, no phone filter on the voice, no studio voice, no voiceover booth sound, no compressed even level, "
 "no crowd noise, no theatrical acting, no speech directed at the camera, no subtitles, no text on screen, no slow motion.")
if __name__=="__main__":
    print(len(VOICE_JOAN), len(VOICE_JOAN.split('. ')[0].split()), len(SEED), len(SEEDANCE))
