PROPERTY = [
 ("1 · Type and era","A 1930s bay-fronted semi-detached house, modernised in the 1980s–90s (uPVC windows and doors, artex swirl ceilings), lived in by the same couple for decades"),
 ("2 · Shell","Cream emulsion walls; white ogee skirting and plain white architrave; sapele-veneer flush internal doors with brass lever handles; artex swirl ceilings; sage-green carpet with a small cream-and-rose floral motif in hall, stairs, landing, bedroom and living room, changing to beige vinyl tile at the kitchen threshold; white steel panel radiators; white plastic switches and sockets"),
 ("3 · Floor map","Front door opens into the hall. Stairs rise straight up the left wall from just inside the door to the landing. Living room through the door on the right. Kitchen straight ahead at the end of the hall, with the back door beside its window. Upstairs: landing at the top with a side window; the main bedroom at the back, over the kitchen"),
 ("4 · Orientation","Front faces east: hall door glass, living-room bay. Back faces west: kitchen window, back door, main bedroom. Landing window on the north side, facing the neighbour's wall. So the front rooms get morning sun and soft afternoon light; the kitchen gets soft morning light and low warm sun in the afternoon"),
 ("5 · Carried elements","The sage floral carpet through five rooms · brass hexagonal lantern in the hall, seen from the stairs · framed family photos up the stair wall and wedding photos on the living-room mantel · sapele doors with brass levers · white panel radiators"),
 ("6 · Exterior","Front: bay window and a uPVC door with frosted glass onto a quiet residential street. Back: lawn, rotary washing line, close-board fence, neighbouring roofs. The kitchen window and the bedroom window both look over the back garden"),
 ("7 · Standing negatives","None observed yet (no frames generated). Recorded 24 Sep 2026: the hall plate's stair wall lacks the brass-bracket wall rail seen in the landing plate"),
]
PROPERTY_PLATE = ("The supplied hall plate is already the §30G property-plate composition: the hall from just inside the front door, the stairs on one side, "
  "an open doorway through to the kitchen, and every shell element readable. It passes the plate check (one age of building, daylight from the door glass "
  "and the far doorway, nobody in frame, lived-in not staged) once the wall rail is added (D13). Recommend locking it as the property plate and attaching it "
  "to every interior beat of the house.")

# tier per §30C 1a: PLATED (camera returns to one spot) · TRAVERSED (subject moves through) · INCIDENTAL (one beat)
LOCS = [
 dict(id="L-KIT",name="Kitchen",tier="PLATED",beats="55 shots · HKC, SC02, SC05, SC10",plate="Supplied · pass",
  prop="Back of the house (west). Door from the hall at the near end; back door right of the window. Window shows the back lawn, rotary line, fence and neighbours' roofs (VIEW-OUT)",
  geo="Galley: window on the far end wall; cabinets, hob and sink run down the left wall; the drop-leaf table and two chairs sit against the right wall by the fridge-freezer; hall door at the camera end, right",
  anchors="The cream retro radio on the windowsill · the floral oilcloth on the drop-leaf table with two pine chairs · the teal border-tile stripe · the chrome kettle beside the white gas hob · the cork board of postcards with the calendar under it",
  loose="Stairlift brochure (SC02: slid across, left untouched) · tea tray with one cup (SC02, counter) · two pills, gel, brace, ice pack (SC05: lined up on the table) · mugs · the mug that breaks (HKC only)",
  palette="Cream walls, maple-effect shaker cabinets with brass cup handles, speckled beige laminate worktop, beige vinyl tile with a worn patch, teal tile accent",
  light="Key from the west window at the end of the galley. Morning (SC05): soft, cool, no direct sun. Afternoon (SC02): overcast, soft. Late afternoon (SC10): low warm sun raking across the floor. Hook C moved to late-afternoon daylight (S2)"),
 dict(id="L-HALL",name="Hall and front door",tier="PLATED + PROPERTY PLATE",beats="14 shots · SC08, and the foot of the stairs in HKA and SC09",plate="Supplied · redress (D13)",
  prop="Front (east). Front door behind camera-left; stairs up the left wall; living-room door right; kitchen visible through the end door (SIGHT-LINE: the kitchen lit by its own west window)",
  geo="Long narrow hall; front door at one end, kitchen door at the other; stairs rising along the left wall from near the door",
  anchors="The frosted-glass uPVC front door with its brass letterbox · the hexagonal brass lantern · the brass coat hooks with a navy and a stone jacket · the mahogany telephone table with the cream corded phone · the coir doormat",
  loose="Shopping bags (HKA: dropped on the carpet; SC08: carried in and set down) · Frank's coat (SC08: half on) · slippers by the mat",
  palette="Cream walls, sage floral carpet, white panelled balustrade, dark sapele handrail, brass fittings",
  light="Soft skylight through the east door glass; in the afternoon the far end glows warm from the kitchen's west window, as the plate already shows"),
 dict(id="L-STAIR",name="Stairs and landing",tier="TRAVERSED (flight) + PLATED (landing)",beats="Flight: 7 moving shots (HKA, SC06, SC09). Landing: 8 dialogue shots at the top",plate="Supplied landing plate · pass",
  prop="Straight flight from the hall to the landing; landing window on the north side. Traversed beats carry the property plate, a GEO-LINE (descending = towards the front door) and one landmark named in prose: the brass-capped newel post at the top",
  geo="About 13 treads, balustrade on the left going down, photo wall and wall rail on the right going down; landing at the top with the laundry basket and radiator",
  anchors="The newel post with its brass pyramid cap · brass stair rods on every tread · the brass-bracket wall rail · framed family photos climbing the wall · the wicker laundry basket on the landing",
  loose="None carried",
  palette="Sage floral carpet with brass rods, white gloss panelling, dark sapele handrail, cream walls",
  light="Landing window high on the left (north): flat, soft; the frosted front door glows at the foot"),
 dict(id="L-BED",name="Main bedroom",tier="PLATED",beats="7 shots · SC03, plus the brace-drawer insert in SC02",plate="Supplied · redress (D15)",
  prop="Back (west), over the kitchen; door to the landing. Window over the back gardens and neighbours' backs (VIEW-OUT)",
  geo="Window on the far wall; bed against the right wall with the bedside table on the right; door ajar on the left; wardrobe and chest either side of the window",
  anchors="The quilted ivory bedspread with the fringed waffle throw · the dark-wood wardrobe · the chest with its open drawer of old knee braces · the bedside table with glasses, water glass and blister packs · floral curtains over nets",
  loose="Glasses and blister pack (constant) · the brace drawer (open, constant)",
  palette="Cream walls, sage carpet, dark wood, ivory bedding, faded floral curtains",
  light="Night: cool streetlight glow through the nets, a sliver of warm landing light at the door. S2 wants a lamp in frame: add a bedside lamp, switched off (D15)"),
 dict(id="L-LIV",name="Living room",tier="PLATED",beats="6 shots · SC11",plate="Supplied · pass",
  prop="Front (east), bay window onto the street through nets; door to the hall",
  geo="Bay on the far wall; fireplace on the right wall; sofa on the left; armchair in the bay",
  anchors="The dusky-pink wingback armchair with a lace antimacassar in the bay · the matching pink sofa · the nest of mahogany tables with the cordless phone · the marble fire surround with the brass gas fire · wedding photos on the mantel",
  loose="Cordless phone (SC11: in Margaret's hand) · two straps (SC11: in hand) · newspaper and glasses on the side table",
  palette="Cream walls, sage carpet, dusky pink upholstery, pale marble, brass",
  light="Afternoon: soft even light from the east bay, no direct sun"),
 dict(id="L-WED",name="Wedding reception room",tier="PLATED · standalone",beats="9 shots · SC04",plate="Supplied · pass (stays empty; guests go in the scene master)",
  prop="Golf-club function room, not part of the house",
  geo="Dance floor in the middle; DJ booth in the corner between two window walls; round tables around the floor; cake table by the picture window",
  anchors="The parquet dance floor with its brass edge strip · the DJ booth with the four-head light bar and two speakers · the three-tier cake by the picture window · the leaded windows onto the course · fairy lights strung across the ceiling",
  loose="Champagne flutes, crackers, confetti on the tables",
  palette="Cream and ivory linen, honey parquet, brown carpet, green fairway outside",
  light="Late-afternoon low sun through the picture window; fairy lights as practicals. Kept in daylight so SC03 is the film's only night (S2)"),
 dict(id="L-GP",name="Doctor's consulting room",tier="PLATED · standalone",beats="7 shots · SC07",plate="Supplied · fix monitor (D9)",
  prop="Standalone clinic room",
  geo="L-shaped desk on the left with the monitor; exam couch under the window on the right; two chairs in front of the desk; door on the back wall",
  anchors="The monitor showing a knee X-ray · the anatomical knee model on the desk · the blue exam couch with its paper roll · vertical blinds onto the car park · two grey plastic chairs",
  loose="Glove box · X-ray on screen (to be a bilateral film with no letters)",
  palette="Magnolia walls, grey dado rail, warm wood desk, blue vinyl couch, green-tinted ceiling panels",
  light="Window on the right, flat overhead panels, midday"),
 dict(id="L-STN",name="Station staircase",tier="TRAVERSED · standalone",beats="6 shots · Hook B",plate="Not needed: a traversed location takes no plate",
  prop="Public; not part of the house",
  geo="A wide commuter staircase with a rail at each side and one down the middle. GEO-LINE: the crowd descends towards camera; Margaret comes down the centre",
  anchors="Landmark carried in prose: the brushed-steel centre handrail",
  loose="Lanyard, handbag",
  palette="Concrete, steel, tiled walls, commuters in dark coats",
  light="Morning daylight from the concourse above, in the warm After grade"),
]

SETCHECKS = [
 ("C0 · one dwelling","Kitchen, hall, stairs and landing, bedroom and living room are one house. The Property Sheet comes first","PASS"),
 ("S1 · tiers","Six PLATED, two TRAVERSED (the stair flight and the station), none INCIDENTAL. The station no longer needs a plate","PASS"),
 ("S2 · at most one evening, with a lamp in frame","Was three (Hook C evening, SC03 night, wedding dusk). Hook C and the wedding moved to daylight; SC03 stays night and needs a bedside lamp in the bedroom plate (D15)","FIXED"),
 ("S3 · light matches orientation","Front east, back west. The kitchen gets the afternoon sun (SC10) and the front door stays soft (SC08), matching what the supplied plates already show","PASS"),
 ("S4 · consecutive acts change rooms","HKA→SC02, SC03→SC04, SC06→SC07, SC10→SC11 all change rooms. With Hook C, both the hook and SC02 are in the kitchen (D16). SC05 runs across the PB/TN boundary as one continuous scene","FLAG"),
 ("Plate consistency across rooms","Carpet, walls, ceilings, doors and brass fittings match in all five house plates. The only mismatch is the missing wall rail on the hall plate (D13)","FLAG"),
]
NEW_DECISIONS = [
 ("D13","Hall plate handrail, and the property plate","The landing plate shows a brass-bracket wall rail; the hall plate's stair wall has none. The hall plate is also exactly the property-plate composition §30G asks for.","Redress the hall plate with the wall rail, then lock it as the property plate. It gets attached to every interior beat of the house"),
 ("D14","Hand on the rail in Scene 5 (SC06)","§30D bans any support in a capability demonstration, and says a hand hovering near a rail counts as touching. The script has Barbara say 'hand on the rail' and Margaret say 'I'm not gripping it'.","Recommend playing it as scripted: her hand rests open on the rail without gripping, and the rule applies from the Doctor scene on. The standard outranks the script, so this needs your OK. Without it, her hands stay off the rail"),
 ("D15","Bedroom lamp","S2 allows one evening location, and it needs a lamp in frame. The bedroom plate has none.","Add a bedside lamp, switched off, to the bedroom plate. The scene stays lit by the streetlight through the nets"),
 ("D16","Hook C and Scene 1 share the kitchen","When Hook C runs, the hook and Scene 1 happen in the same room back to back, which weakens the cut into the story.","Keep it. The time card, the move from late afternoon to overcast, and a change of outfit carry the jump"),
]
