SCENES = [
 dict(id="HKA-SC01",act="HK",title="Hook A · 'Get away'",day="HKA",loc="L-STAIR + L-HALL",time="Morning, overcast; cool grey grade",cast="Margaret · Sarah",
      axis="Stair line, camera on the photo-wall side; Sarah enters from the front door",route="MULTI-SHOT (Seedance)",
      emo="Margaret: pride → shame. Sarah: alarm → hurt. Subtext: she's ashamed, not angry",props="Shopping bags: carried → dropped on the hall carpet",tin="Cold open",tout="CARD '6 weeks ago' → SC02"),
 dict(id="HKB-SC01",act="HK",title="Hook B · 'Seventy-one!'",day="HKB",loc="L-STN (to generate)",time="Rush hour, bright; warm AF grade",cast="Margaret · W1 · W2",
      axis="Down the staircase, camera below looking up the middle rail",route="MULTI-SHOT (Seedance)",
      emo="Women: weary → disbelief. Margaret: hurried joy. Flash-forward",props="Lanyard, handbag",tin="Cold open",tout="CARD '6 weeks ago' → SC02"),
 dict(id="HKC-SC01",act="HK",title="Hook C · The floor",day="HKC",loc="L-KIT",time="Evening, overhead light; cool grey grade",cast="Margaret · Frank",
      axis="Along the galley; camera at the window end",route="MULTI-SHOT (Seedance)",
      emo="Margaret: pain → fear for him. Frank: fear held → stubborn love",props="Mug: counter → broken on the floor",tin="Cold open",tout="CARD '6 weeks ago' → SC02"),
 dict(id="BF-SC02",act="BF",title="Scene 1 · Kitchen",day="D1",loc="L-KIT",time="Afternoon, overcast window light",cast="Margaret · Sarah",
      axis="Across the drop-leaf table; Margaret window side, Sarah door side",route="MULTI-SHOT (Seedance)",
      emo="Sarah: pleading → cracking. Margaret: closed → frightened. Subtext: she thinks a stairlift is the first step to a care home",props="Brochure: slid across → untouched; tea tray waiting on the counter",tin="From card",tout="CUT on her eyes to the stairs → SC03 dark"),
 dict(id="BF-SC03",act="BF",title="Scene 2 · Bedroom, that night",day="D1 (nightwear)",loc="L-BED",time="Night: streetlight through nets",cast="Margaret · Frank",
      axis="Across the pillows; camera on Frank's side",route="MULTI-SHOT (Seedance)",
      emo="Frank: fear spoken. Margaret: masking → awake and afraid",props="Glasses and blister pack on the bedside table",tin="CUT from the stairs",tout="CUT to the wedding's noise"),
 dict(id="PB-SC04",act="PB",title="Scene 3 · Emily's wedding",day="D2",loc="L-WED",time="Golden hour into fairy lights",cast="Margaret · Frank · Emily · Barbara (dancing) · guests",
      axis="Margaret's table to the dance floor",route="MULTI-SHOT + inserts",
      emo="Emily: hope → deflated. Margaret: grief behind a smile → envy, dawning",props="Champagne glasses; Emily's hands",tin="CUT",tout="CUT to the pills lined up → SC05"),
 dict(id="PB/TN-SC05",act="PB→TN",title="Scene 4 · Kitchen, a week later",day="D3",loc="L-KIT",time="Morning, soft window light warming",cast="Margaret · Barbara",
      axis="Across the table; Barbara door side, Margaret window side",route="MULTI-SHOT dialogue + Kling inserts + §12A renders",
      emo="Margaret: resigned → sceptical → raw → a crack of hope. Barbara: probing → candid → dry kindness. TURN: 'I'm 74, Margaret. I haven't got time to lie to you.'",
      props="Pills, gel, brace, ice pack lined up; Barbara's phone; the strap: Barbara's leg → Margaret's palm",tin="MATCH CUT from wedding hands to pills",tout="CONTINUOUS to the stairs"),
 dict(id="TN-SC06",act="TN",title="Scene 5 · The stairs",day="D3",loc="L-STAIR (+ hall reverse)",time="Late morning, landing window",cast="Margaret · Barbara",
      axis="Stair line held from Hook A; camera on the photo-wall side",route="Singles + uncut descent (Seedance)",
      emo="Margaret: terror → wonder → release. Barbara: steady → moved → brisk",props="Strap on Margaret's right knee; trouser leg drawn up above the knee and staying there",tin="CONTINUOUS",tout="CARD 'A month later' → SC07"),
 dict(id="AF-SC07",act="AF",title="Scene 6 · Doctor's office",day="D4",loc="L-GP",time="Midday, blinds and panel light",cast="Margaret · Doctor",
      axis="Across the desk; monitor on the doctor's side",route="MULTI-SHOT (Seedance)",
      emo="Doctor: clinical → curious → approving. Margaret: quiet pride → wry",props="X-ray on monitor (no numerals); knee model",tin="From card",tout="CUT to the front door opening"),
 dict(id="AF-SC08",act="AF",title="Scene 7 · Front door",day="D5",loc="L-HALL",time="Late afternoon, low sun through the frosted door",cast="Margaret · Frank",
      axis="Hall line, door to kitchen; camera on the coat-hook side",route="MULTI-SHOT (Seedance)",
      emo="Frank: worry → astonished → breaking. Margaret: calm → tender resolve",props="Two shopping bags: carried in → set down (mirror of Hook A)",tin="CUT",tout="TIME CUT: same hall, Sunday"),
 dict(id="AF-SC09",act="AF",title="Scene 8a · Sunday, the stairs",day="D6",loc="L-STAIR + L-HALL",time="Sunday midday, bright",cast="Margaret · Sarah",
      axis="Stair line from Hook A, reversed to going up",route="Singles (Seedance)",
      emo="Sarah: habit → stunned → wonder. Margaret: gentle mischief → assured",props="Trouser leg pulled up at the top",tin="TIME CUT",tout="TIME CUT: 'Later', kitchen radio"),
 dict(id="AF-SC10",act="AF",title="Scene 8b · Kitchen dance",day="D6",loc="L-KIT",time="Sunday afternoon, warm low sun",cast="Margaret · Emily · Sarah",
      axis="Galley length; Sarah in the doorway",route="Uncut dance (Seedance)",
      emo="Emily: playful. Margaret: joy. Sarah: laughing and crying",props="Radio on",tin="TIME CUT",tout="CUT to the living room"),
 dict(id="OC-SC11",act="OC",title="Scene 9 · Phone call",day="D7",loc="L-LIV",time="Afternoon, bay window",cast="Margaret · Joan (voice only)",
      axis="Armchair in the bay; camera from the fireplace side",route="Singles (Seedance) + Kling insert",
      emo="Margaret: purpose → warm certainty. Joan: weary → persuaded",props="Cordless phone; two straps in hand",tin="CUT",tout="Declared break → end card"),
 dict(id="OC-SC12",act="OC",title="End card",day="—",loc="Sweep (SURF-SWEEP)",time="Film LUT",cast="—",
      axis="—",route="Kling or Seedance single",
      emo="Trust",props="Two units + packaging",tin="Declared register break",tout="End"),
]

# Wardrobe map — one outfit row per story day per subject (§21, §14A)
# BASE · MID · OUTER · LOWER · FOOT · ACCENT · colour family · visibility
WARD = [
 # story day, subject, BASE, MID, OUTER, LOWER, FOOT, ACCENT, family, events
 ("HKA","Margaret","long-sleeve tee, heather grey","open draped cardigan, charcoal","—","cords, navy","slippers, sheepskin","reading glasses on a bead chain (signature)","cool neutral","HKA-SC01 · stairs + hall · —"),
 ("HKA","Sarah","crew-neck tee, white","—","puffer, black","jeans, mid-blue","trainers, white","bag strap (shopping)","monochrome","HKA-SC01 · hall + stairs"),
 ("HKB","Margaret","blouse, navy","—","rain jacket (belted trench), camel","cropped straight trousers, charcoal, hem mid-calf","trainers, white leather","lanyard · handbag · signature glasses on chain","navy/denim","HKB-SC01 · station · CONCEALED (D4)"),
 ("HKC","Margaret","t-shirt, plum","zip fleece, plum","—","joggers, grey marl","mule slippers, navy felt","signature glasses","red family","HKC-SC01 · kitchen · —"),
 ("HKC","Frank","check shirt, blue","buttoned cable cardigan, oatmeal (signature)","—","trousers, mid-grey flannel","slippers, brown","—","warm neutral","HKC-SC01 · kitchen"),
 ("D1","Margaret","roll-neck, bottle green","—","—","long skirt, grey wool, below the calf","slippers, red tartan","signature glasses","green family","BF-SC02 · kitchen · —"),
 ("D1 night","Margaret","nightdress, cotton, small blue floral","—","—","(nightdress)","bare","—","pattern-led","BF-SC03 · bedroom · nightwear event within D1"),
 ("D1","Sarah","crew jumper worn alone, grey (sheet)","—","—","jeans, black","trainers, white","small gold hoops (signature)","cool neutral","BF-SC02 · kitchen"),
 ("D1 night","Frank","pyjama top, blue-white stripe","—","—","pyjama bottoms, stripe","bare","—","pattern-led","BF-SC03 · bedroom · nightwear event within D1"),
 ("D2","Margaret","dress, dusky-rose chiffon, below the calf","bolero cardigan, cream","—","(dress)","low court shoes, nude","pearl studs · signature glasses in clutch","red family","PB-SC04 · wedding · —"),
 ("D2","Frank","button-down shirt, white","waistcoat, charcoal","suit jacket, charcoal","suit trousers, charcoal","loafers, black","tie, burgundy · buttonhole","monochrome","PB-SC04 · wedding"),
 ("D2","Emily","wedding gown, ivory","—","—","(gown)","—","veil, bouquet","warm neutral","PB-SC04 · wedding"),
 ("D2","Barbara","dress, royal-blue jersey, below the calf","—","—","(dress)","flat sandals, silver","purple glass-bead necklace (signature)","navy/denim","PB-SC04 · dance floor · CONCEALED (strap hidden by hem)"),
 ("D2","Sarah","dress, sage midi","—","—","(dress)","heels, nude","pashmina, cream · signature hoops","green family","PB-SC04 · wedding (background)"),
 ("D3","Margaret","button-down shirt, blue-white Breton stripe","v-neck jumper, navy, sleeves pushed","—","chinos, stone, loose straight leg","plimsolls, navy canvas","signature glasses","navy/denim","PB/TN-SC05 kitchen · — ; TN-SC06 stairs · VISIBLE (right trouser leg drawn up above the knee after fitting, left gathered there)"),
 ("D3","Barbara","t-shirt, purple (sheet)","open draped cardigan, mustard","—","wide-leg trousers, black, loose enough to pull above the knee","socked, grey","signature beads","earth","PB/TN-SC05 · REVEAL (left) ; TN-SC06 · —"),
 ("D4","Margaret","roll-neck, chocolate brown","—","wool coat, camel","wide-leg trousers, charcoal","ankle boots, tan","signature glasses · handbag","earth","AF-SC07 · GP · CONCEALED → REVEAL"),
 ("D4","Doctor","button-down shirt, light blue, sleeves rolled (sheet)","—","—","chinos, navy","brogues, tan","knit tie, navy · blank ID badge turned in","navy/denim","AF-SC07 · GP"),
 ("D5","Margaret","long-sleeve tee, cream","crew jumper, cornflower blue","quilted jacket, navy","jeans, dark indigo","trainers, grey walking","scarf, paisley · two shopping bags","navy/denim","AF-SC08 · hall · CONCEALED"),
 ("D5","Frank","polo shirt, bottle green","buttoned cable cardigan, oatmeal (signature)","wax jacket, olive — half on","cords, brown","loafers, brown suede (sheet)","—","green family","AF-SC08 · hall"),
 ("D6","Margaret","blouse, soft-pink floral","buttoned cardigan, cream","—","wide-leg trousers, navy","slippers, moccasin","signature glasses","pattern-led","AF-SC09 stairs · REVEAL ; AF-SC10 kitchen · CONCEALED"),
 ("D6","Sarah","button-down shirt, chambray","—","—","cords, tan","loafers, brown","signature hoops","earth","AF-SC09 stairs ; AF-SC10 doorway"),
 ("D6","Emily","long-sleeve tee, cream","vintage fair-isle cardigan, rust and teal","—","wide-leg cords, rust","chunky lace-up boots, oxblood","—","pattern-led","AF-SC10 · kitchen · register changed to clear Sarah (§19A)"),
 ("D7","Margaret","tunic, mustard","—","—","leggings, charcoal","slipper boots, grey knit","signature glasses","earth","OC-SC11 · living room · CONCEALED ; two straps HELD"),
]
