import json
exec(open('make_act5_images.py').read().split('\nB = {}')[0])
BR038="9ebf53ea-162d-4e0a-b64f-c25864cd65d6"; MECH040="181510f0-bcb6-46d4-af80-5c8a7a68fb1c"
B={}
B["BR-043"] = P(GAIL+" outside her 1960s pebble-dashed semi, walking down her own short front path towards the low front gate and the pavement, towards the lens, mid-stride: her right foot planted and taking her weight, her left foot swinging through, arms loose, an easy confident stride, the small square front lawn and a clipped privet hedge either side of the concrete path, the house front behind her. A white broderie-anglaise short-sleeved blouse, wide-leg sage-green linen trousers down to the ankle, the trouser legs hanging straight and loose with nothing showing beneath them, a thin gold watch.",
 "the lens low, at waist height in front of her on the path near the gate, looking up the path at her as she comes, from the front. Her whole figure from head to shoes, the house front behind.",
 "everything from near to far stays sharp — the path, her, the house.", OUT_L,
 "no strap, no knee support, no brace, no bandage, no rolled trousers, no bare knees, no bulge at the knee, no product, no running, no posing, no looking at the lens")
B["BR-050"] = P(GAIL+" IN THE SAME HOUSE as the attached hall photograph, standing still on the landing at the top of the stairs, both feet level, her hand resting on the banister post, "+ROLL.replace("both thighs","both thighs, both knees bare to view")+". ONE Stryde strap only, exactly the product in the attached product photographs and worn exactly as in the attached bedroom photograph of her knee — on her right knee; her left knee completely bare. "+W+" "+s.LEG_SKIN+" "+D2,
 "the lens above, from the front, halfway up the stairs looking up and slightly down across to her on the landing, medium: from her waist to her feet, both knees side by side in the middle of the frame, the landing window behind.",
 "both knees and the strap are in sharp focus; the landing window behind falls soft.", HALL2,
 F(s.NEG_PLACE)+", no strap on the left knee, no second strap, no two straps on one knee, no strap above the knee, no strap below the knee as well, no generic knee strap, no plain black band, no velcro strap, no neoprene strap, no strap without the chrome slides, no strap on both knees, no trouser hem over the strap, no stepping, no face")
B["BR-052"] = P(GAIL+" IN THE SAME HOUSE as the attached hall photograph, AT THE TOP OF THE STAIRCASE, beginning to come DOWN it forwards, facing down the flight towards the lens: she stands on the top stair by the landing, her left hand light on the banister rail, and her right foot is reaching down onto the next stair below, the right knee bending over it, her weight still on her left foot on the top stair, upright and relaxed, eyes looking down the stairs ahead. The whole flight of stairs lies between her and the lens. "+ROLL+". "+PROD+" "+F(s.PLACE_BENT)+" "+s.SIZE_WORN+" "+s.LEG_SKIN+" "+D2,
 "the lens low at the FOOT of the stairs, a little above the hall floor, looking UP the whole flight at her at the top from three-quarter front: the steps rising away from the lens, the rail leading up to her, her whole figure small near the top of the frame with the landing window behind her.",
 "everything from near to far stays sharp — the steps, the rail, her, the strap.", HALL2,
 F(s.NEG_BENT)+", no climbing, no going up the stairs, no foot lifted onto a higher step, no back to the lens, no standing at the bottom, no standing in the middle of the flight, no gripping the rail hard, no leaning back, no stiff leg, no running, no trouser hem over the strap, no strap on the left knee, no looking at the lens")
B["MECH-056"] = "\n\n".join([ANATH.replace("in true lateral profile,","in true lateral profile, the knee bent about twenty degrees in the middle of an easy walking step, exactly the same model, look and framing as the attached anatomical frame,"),
 "The product in place on this anatomical knee, exactly as in the attached anatomical frame: "+PROD+" "+F(s.PLACE_LOCK_C),
 "Materials solid and opaque against the translucent anatomy, the chrome slides catching bright specular flares, the wordmark readable. The band sits snug round the leg and the rigid shell rests firmly on the tendon, carrying the load.",
 "STATE — RELIEF. The pad inside the shell holds a soft cool pale-blue glow where it carries the load; beneath it the patellar tendon immediately below the patella is cool, pale and calm, no heat anywhere at the site. The whole knee reads calm and even.",
 "AVOID: no orange glow, no red glow, no hot spot under the strap, no bright site, no product floating off the tendon, no product on the kneecap, no glow on the bones, "+F(s.NEG_WARP_P)+", "+ANEG.replace("no clothing,","")])+"\n"
B["PR-045"] = P("An orthopaedic surgeon in his fifties — kind, approachable, a slight smile, short grey hair, reading glasses pushed up on his head, a pale blue cotton shirt with the sleeves rolled to the forearm, no white coat, no stethoscope — IN THE SAME CONSULTING ROOM as the attached room photograph, sitting at the desk beside a life-size anatomical knee model on its stand. In his right hand, near the knee model, he holds the strap. "+PROD+" held in a bottom-edge pinch: thumb in front on the shell's bottom edge below the wordmark, fingers behind on the pad, the band hanging slack below; nothing rises above the shell's top edge, the peaks and notch clear, the wordmark facing the lens. TRUE TO SIZE: it is a small, slim strap — the shell is only about twelve centimetres across, no wider than his palm and a little more, about as tall as his thumb is long, clearly smaller than his whole hand; beside the life-size knee model it is exactly the size to fit across the front of that model's knee below its kneecap. It is small in the frame, held in one hand, never filling the frame.",
 "the lens at his eye height, level, seen from three-quarter of him across the corner of the desk, medium: his head and shoulders, his hand holding the small strap and the knee model beside it in the frame, the strap at its true small size.",
 "the strap in his hand is in sharp focus; his face just soft; the room behind falls to a soft, recognisable shape.",
 "THE LIGHT: daylight from the consulting-room window to the left of the frame, soft and even, a little warm, so he has a lit side toward the left. The shadows fall away from the window, one way only.",
 s.NEG_HELD_P+", "+F(s.NEG_WARP_P)+", no oversized strap, no strap bigger than his hand, no strap wider than his palm and fingers, no strap filling the frame, no strap held close to the lens, no forced perspective, no white coat, no stethoscope, no scrubs, no mask, no stern face, no strap on the knee model, no second strap, no looking at the lens")
REFS = {"R1":"39306d36-3fbe-43ab-a8a8-43fc3d63b61c","P0":"75740289-c52e-4333-a7ca-30df059f68e6","P6":"26f471c2-5878-4a54-9e2a-d034ce7fd9e6","front":"7106f755-c1f5-4d61-b948-4462ed654dfe","back":"b461416e-189b-470b-9fc9-cb77da229ead","worn_front":"f5263ed7-0667-4ebd-977e-9bfd835d5036","BR038":BR038,"MECH040":MECH040}
PLAN2={"BR-043":("nano_banana_2",["R1"]),"BR-050":("nano_banana_pro",["R1","BR038","front","back"]),
       "BR-052":("nano_banana_pro",["R1","P0","front","back"]),"MECH-056":("nano_banana_pro",["MECH040","front","back"]),
       "PR-045":("nano_banana_pro",["P6","front","back"])}
req=[]
for i,(b,t) in enumerate(B.items()):
    if PLAN2[b][0]=="nano_banana_pro": t=t.replace("no readable text, no logos","no other text, no other logos")
    open(b+".txt","w").write(t)
    req.append({"index":i,"params":{"model":PLAN2[b][0],"aspect_ratio":"9:16","resolution":"2k","count":1,"use_unlim":False,
      "medias":[{"value":REFS[r],"role":"image_references"} for r in PLAN2[b][1]],"prompt":t}})
    print(b,len(t),PLAN2[b])
json.dump({b:PLAN2[b] for b in B},open("refs_v2.json","w"))
json.dump(req,open("/tmp/claude-0/-home-user-global-manual-ai/20b2c4f7-1437-5cc0-b561-f96976bb11e8/scratchpad/a5v2_req.json","w"),ensure_ascii=False)
